do $$declare f text:=pg_get_functiondef('public.get_company_profit_summary()'::regprocedure);begin
 if to_regprocedure('public.confirm_deal_deposit(uuid,numeric,text,uuid,text)')is null or to_regprocedure('public.confirm_deal_internal_payment(uuid,numeric,text,uuid,text)')is null or to_regprocedure('public.record_deal_procurement_cost(uuid,numeric,text,uuid)')is null or to_regprocedure('public.record_deal_sales_expense(uuid,numeric,text,uuid)')is null then raise exception'Legacy write RPC upgrade incomplete';end if;
 if to_regprocedure('public.get_company_profit_summary()')is null or position('security definer' in lower(f))=0 then raise exception'Secure company summary missing';end if;
 if position('deal_payments' in f)>0 or position('deal_payment_reversals' in f)>0 then raise exception'Customer payments leak into company profit';end if;
 if position('has_access_role' in f)=0 or position('finance.read' in f)=0 or position('customers.supervise' in f)>0 then raise exception'Company summary role boundary unsafe';end if;
 if exists(select 1 from pg_policies where schemaname='public'and policyname in('owner reads company internal settlements','owner reads company procurement costs','owner reads company orders for forecast','owner reads company adjustments v2'))then raise exception'Owner still has raw company ledger access';end if;
 if position('can_supervise_performance' in pg_get_viewdef('public.supervisor_order_margin'::regclass,true))=0 or position('q.owner_id = auth.uid()' in pg_get_viewdef('public.personal_sales_margin'::regclass,true))=0 then raise exception'Supervisor or sales margin boundary changed';end if;
 if has_function_privilege('anon','public.get_company_profit_summary()','EXECUTE')or has_table_privilege('anon','public.company_profit_summary','SELECT')then raise exception'Anonymous company profit access';end if;
 if position('finance.manage' in pg_get_functiondef('public.confirm_deal_deposit(uuid,numeric,text,uuid,text)'::regprocedure))=0 or position('finance.manage' in pg_get_functiondef('public.record_deal_procurement_cost(uuid,numeric,text,uuid)'::regprocedure))=0 then raise exception'Finance write authorization missing';end if;
end$$;select'dual_ledger_secure_upgrade_ok'result;
