do$$begin
 if to_regclass('public.notification_jobs')is null or to_regclass('public.notification_attempts')is null or to_regclass('public.notification_supervisor_exceptions')is null then raise exception'Notification tables missing';end if;
 if position('09:30' in pg_get_functiondef('public.enqueue_wecom_notification_jobs(text,timestamp with time zone)'::regprocedure))=0 or position('appointment_day_before' in pg_get_functiondef('public.enqueue_wecom_notification_jobs(text,timestamp with time zone)'::regprocedure))=0 or position('2 hours' in pg_get_functiondef('public.enqueue_wecom_notification_jobs(text,timestamp with time zone)'::regprocedure))=0 then raise exception'Notification schedules missing';end if;
 if position('on conflict' in lower(pg_get_functiondef('public.enqueue_wecom_notification_jobs(text,timestamp with time zone)'::regprocedure)))=0 then raise exception'Idempotent enqueue missing';end if;
 if position('attempt_no >= 5' in pg_get_functiondef('public.complete_wecom_notification_job(uuid,boolean,text,text,timestamp with time zone)'::regprocedure))=0 or position('power(2' in pg_get_functiondef('public.complete_wecom_notification_job(uuid,boolean,text,text,timestamp with time zone)'::regprocedure))=0 then raise exception'Retry cap/backoff missing';end if;
 if position('notification_supervisor_exceptions' in pg_get_functiondef('public.complete_wecom_notification_job(uuid,boolean,text,text,timestamp with time zone)'::regprocedure))=0 or position('audit_logs' in pg_get_functiondef('public.complete_wecom_notification_job(uuid,boolean,text,text,timestamp with time zone)'::regprocedure))=0 then raise exception'Final failure escalation missing';end if;
 if has_function_privilege('authenticated','public.claim_wecom_notification_jobs(integer,timestamp with time zone)','EXECUTE')or has_function_privilege('anon','public.claim_wecom_notification_jobs(integer,timestamp with time zone)','EXECUTE')then raise exception'Notification worker RPC exposed';end if;
 if(select count(*)from pg_policies where schemaname='public'and tablename like'notification_%'and policyname='sales os v3 server gate'and permissive='RESTRICTIVE')<>3 then raise exception'Notification gates missing';end if;
 if not exists(select 1 from pg_constraint where conrelid='public.notification_jobs'::regclass and contype='c'and pg_get_constraintdef(oid)like'%phone%amount%profit%')then raise exception'Sensitive payload guard missing';end if;
 if exists(select 1 from pg_policies where schemaname='public'and tablename='notification_attempts'and cmd in('INSERT','UPDATE','DELETE','ALL'))then raise exception'Attempt history client-mutable';end if;
end$$;select'notification_core_ok'result;
