import { useEffect, useState } from 'react'
import { ArrowLeft, Layers3, Pencil, Plus, Save, Trash2, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { PackageDataSource } from './packageDataSource'
import type { PackageDraft, PackageSnapshot, PackageView } from './packageTypes'

const businesses = [['fast_food','快餐'],['chinese','中餐'],['hotpot','火锅'],['barbecue','烧烤'],['beverage','饮品'],['bakery','烘焙'],['banquet','宴会'],['international','异国料理']] as const
const blank = (): PackageDraft => ({ code: '', name: '', businessType: 'chinese', isActive: true, lines: [{ catalogItemId: '', quantity: 1 }] })

export function PackageAdminPage({ dataSource }: { dataSource: PackageDataSource }) {
  const [snapshot, setSnapshot] = useState<PackageSnapshot | null>(null)
  const [draft, setDraft] = useState<PackageDraft | null>(null)
  const [busy, setBusy] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const load = async () => { setBusy(true); setError(''); try { setSnapshot(await dataSource.loadSnapshot()) } catch (reason) { setError(reason instanceof Error ? reason.message : '读取套餐失败') } finally { setBusy(false) } }
  useEffect(() => { let active = true; dataSource.loadSnapshot().then((value) => { if (active) setSnapshot(value) }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : '读取套餐失败') }).finally(() => { if (active) setBusy(false) }); return () => { active = false } }, [dataSource])
  const edit = (pkg: PackageView) => setDraft({ ...pkg, lines: pkg.lines.map((line) => ({ ...line })) })
  const patchLine = (index: number, patch: Partial<PackageDraft['lines'][number]>) => draft && setDraft({ ...draft, lines: draft.lines.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line) })
  const save = async () => {
    if (!draft?.code.trim() || !draft.name.trim() || draft.lines.some((line) => !line.catalogItemId || !(line.quantity > 0))) { setError('请填写套餐编码、名称和有效商品数量'); return }
    setBusy(true); setError(''); setNotice('')
    try { await dataSource.savePackage(draft, crypto.randomUUID()); setDraft(null); await load(); setNotice('套餐配置已保存并实时生效') }
    catch (reason) { setError(reason instanceof Error ? reason.message : '保存套餐失败') }
    finally { setBusy(false) }
  }
  const items = snapshot?.items ?? []
  return <section className="mx-auto w-full max-w-6xl pb-12">
    <Link to="/settings-v3/catalog" className="mb-4 inline-flex items-center gap-2 rounded-lg px-2 py-2 text-sm font-medium text-slate-600 hover:bg-white"><ArrowLeft size={17}/>返回商品配置</Link>
    <header className="rounded-2xl bg-slate-950 px-5 py-6 text-white shadow-lg sm:px-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.2em] text-violet-300">当前套餐配置</p><h1 className="mt-2 text-2xl font-semibold">套餐内容配置</h1><p className="mt-2 text-sm text-slate-300">保存后实时更新销售报价；销售可调整套餐总售价，但不能改变套餐组成。</p></div><button onClick={() => setDraft(blank())} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-300 px-4 text-sm font-semibold text-slate-950"><Plus size={18}/>新增套餐</button></div></header>
    {error && <div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice && <div role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}
    <div className="mt-5 grid gap-3 md:grid-cols-2">{snapshot?.packages.map((pkg) => <article key={pkg.id} className={`rounded-2xl border bg-white p-4 shadow-sm ${pkg.isActive ? 'border-slate-200' : 'opacity-65'}`}><div className="flex items-start justify-between"><div><div className="flex flex-wrap gap-2"><strong>{pkg.name}</strong><span className="rounded bg-slate-100 px-2 font-mono text-xs">{pkg.code}</span>{!pkg.isActive && <span className="rounded bg-slate-200 px-2 text-xs">已停用</span>}</div><p className="mt-2 text-xs text-slate-500">{businesses.find(([value]) => value === pkg.businessType)?.[1]} · {pkg.lines.length} 项固定内容</p></div><button aria-label={`编辑${pkg.name}`} onClick={() => edit(pkg)} className="rounded-lg border p-2"><Pencil size={16}/></button></div><div className="mt-3 grid gap-1 text-sm text-slate-600">{pkg.lines.map((line) => <span key={line.catalogItemId}>{items.find((item) => item.id === line.catalogItemId)?.name ?? '已停用商品'} × {line.quantity}</span>)}</div></article>)}{!busy && snapshot?.packages.length === 0 && <p className="col-span-full rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">当前没有套餐。</p>}</div>
    {draft && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-4" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-2xl bg-white p-5 sm:rounded-2xl"><div className="flex justify-between"><h2 className="text-xl font-semibold">{draft.id ? '编辑套餐' : '新增套餐'}</h2><button aria-label="关闭" onClick={() => setDraft(null)}><X/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="套餐编码"><input value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value })}/></Field><Field label="套餐名称"><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></Field><Field label="适用业态"><select value={draft.businessType} onChange={(event) => setDraft({ ...draft, businessType: event.target.value })}>{businesses.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></Field><label className="flex items-center justify-between rounded-xl border p-3 text-sm">启用套餐<input type="checkbox" checked={draft.isActive} onChange={(event) => setDraft({ ...draft, isActive: event.target.checked })}/></label></div>
      <fieldset className="mt-4"><legend className="font-medium">固定套餐内容</legend><div className="mt-2 grid gap-2">{draft.lines.map((line,index) => <div key={index} className="grid grid-cols-[1fr_90px_40px] gap-2"><select value={line.catalogItemId} onChange={(event) => patchLine(index, { catalogItemId: event.target.value })} className="min-h-11 rounded-xl border bg-white px-2"><option value="">选择软件、硬件或加购项目</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.sku}</option>)}</select><input aria-label="数量" type="number" min="0.01" step="0.01" value={line.quantity} onChange={(event) => patchLine(index, { quantity: Number(event.target.value) })} className="rounded-xl border px-2"/><button aria-label="删除套餐内容" disabled={draft.lines.length === 1} onClick={() => setDraft({ ...draft, lines: draft.lines.filter((_,lineIndex) => lineIndex !== index) })} className="rounded-xl border text-red-600 disabled:opacity-30"><Trash2 size={16} className="mx-auto"/></button></div>)}</div><button onClick={() => setDraft({ ...draft, lines: [...draft.lines, { catalogItemId: '', quantity: 1 }] })} className="mt-2 inline-flex min-h-10 items-center gap-2 rounded-lg border px-3 text-sm"><Layers3 size={16}/>增加内容</button></fieldset>
      <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">特殊内容不在这里修改，必须进入主管审批流程。</p><div className="mt-5 flex gap-3"><button onClick={() => setDraft(null)} className="min-h-11 flex-1 rounded-xl border">取消</button><button disabled={busy} onClick={() => void save()} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-950 font-semibold text-white disabled:opacity-50"><Save size={17}/>保存并生效</button></div></div></div>}
  </section>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm">{label}<span className="mt-1 block [&_input]:min-h-11 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:px-3 [&_select]:min-h-11 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:bg-white [&_select]:px-3">{children}</span></label> }
