import { useCallback, useEffect, useState } from 'react'
import type { CrmEditorOptions, SalesWorkbenchDataSource } from './dataSource'

type Kind='brand'|'store'|'contact'|'lead'
const empty={id:'',name:'',businessMode:'independent',brandId:'',regionId:'',storeId:'',businessType:'chinese',address:'',title:'',source:'',isKeyPerson:false}
export function CrmEntityEditor({dataSource,onSaved}:{dataSource:SalesWorkbenchDataSource;onSaved:()=>Promise<void>}){
 const [options,setOptions]=useState<CrmEditorOptions|null>(null),[kind,setKind]=useState<Kind>('brand'),[form,setForm]=useState(empty),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(true)
 const load=useCallback(async()=>{setBusy(true);setError('');try{setOptions(await dataSource.loadCrmEditorOptions())}catch(e){setError(e instanceof Error?e.message:'读取编辑数据失败')}finally{setBusy(false)}},[dataSource])
 useEffect(()=>{queueMicrotask(()=>{void load()})},[load])
 const choose=(id:string)=>{if(!options){return}const item=(kind==='brand'?options.brands:kind==='store'?options.stores:kind==='contact'?options.contacts:options.leads).find(x=>x.id===id) as Record<string,unknown>|undefined;setForm(item?{...empty,...item,id}:empty)}
 const save=async()=>{if(!form.name.trim()&&kind!=='lead'){setError('名称必填');return}if(kind==='lead'&&!form.title.trim()){setError('线索标题必填');return}setBusy(true);setError('');setNotice('');try{if(kind==='brand')await dataSource.upsertBrand({id:form.id||undefined,name:form.name,businessMode:form.businessMode});if(kind==='store')await dataSource.upsertStore({id:form.id||undefined,brandId:form.brandId,regionId:form.regionId,name:form.name,businessType:form.businessType,address:form.address});if(kind==='contact')await dataSource.upsertContact({id:form.id||undefined,brandId:form.brandId||undefined,storeId:form.storeId||undefined,name:form.name,title:form.title,isKeyPerson:form.isKeyPerson});if(kind==='lead')await dataSource.upsertLead({id:form.id||undefined,brandId:form.brandId||undefined,storeId:form.storeId||undefined,regionId:form.regionId,title:form.title,source:form.source});setNotice('保存成功');setForm(empty);await load();await onSaved()}catch(e){setError(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}
 if(busy&&!options)return <p className="sw-loading">正在加载CRM编辑数据…</p>
 if(!options)return <div className="sw-data-error">{error}</div>
 const items=kind==='brand'?options.brands:kind==='store'?options.stores:kind==='contact'?options.contacts:options.leads
 return <section className="sw-crm-editor"><h3>新建 / 编辑客户资料</h3><div className="sw-editor-tabs">{(['brand','store','contact','lead'] as Kind[]).map(x=><button className={kind===x?'is-active':''} onClick={()=>{setKind(x);setForm(empty)}} key={x}>{({brand:'品牌',store:'门店',contact:'联系人',lead:'线索'})[x]}</button>)}</div><label>编辑已有记录<select value={form.id} onChange={e=>choose(e.target.value)}><option value="">新建</option>{items.map(x=><option key={x.id} value={x.id}>{'name'in x?x.name:x.title}</option>)}</select></label>
 {(kind==='brand'||kind==='store'||kind==='contact')&&<label>名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}{kind==='brand'&&<label>经营模式<select value={form.businessMode} onChange={e=>setForm({...form,businessMode:e.target.value})}><option value="independent">独立门店</option><option value="direct_chain">直营连锁</option><option value="franchise_chain">加盟连锁</option></select></label>}
 {(kind==='store'||kind==='contact'||kind==='lead')&&<label>品牌<select value={form.brandId} onChange={e=>setForm({...form,brandId:e.target.value})}><option value="">请选择</option>{options.brands.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 {(kind==='store'||kind==='lead')&&<label>区域<select value={form.regionId} onChange={e=>setForm({...form,regionId:e.target.value})}><option value="">请选择</option>{options.regions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 {(kind==='contact'||kind==='lead')&&<label>门店<select value={form.storeId} onChange={e=>setForm({...form,storeId:e.target.value})}><option value="">请选择</option>{options.stores.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}
 {kind==='store'&&<><label>业态<select value={form.businessType} onChange={e=>setForm({...form,businessType:e.target.value})}>{['fast_food','chinese','hotpot','barbecue','beverage','bakery','banquet','international'].map(x=><option key={x}>{x}</option>)}</select></label><label>地址<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></>}
 {kind==='contact'&&<><label>职务<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="sw-check"><input type="checkbox" checked={form.isKeyPerson} onChange={e=>setForm({...form,isKeyPerson:e.target.checked})}/>关键人</label></>}
 {kind==='lead'&&<><label>线索标题<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>来源<input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label></>}{error&&<div className="sw-data-error">{error}</div>}{notice&&<div className="sw-success">{notice}</div>}<button className="sw-primary" disabled={busy} onClick={save}>{busy?'正在保存…':'通过安全RPC保存'}</button></section>
}
