import { useEffect, useState } from 'react'
import type { CrmEditorOptions, QualificationStatus, SalesWorkbenchDataSource } from './dataSource'

export function QualificationEvidenceEditor({ leadId, dataSource, onQualified }: { leadId: string; dataSource: SalesWorkbenchDataSource; onQualified: () => Promise<void> }) {
  const [opts, setOpts] = useState<CrmEditorOptions | null>(null); const [status, setStatus] = useState<QualificationStatus | null>(null)
  const [contactName, setContactName] = useState(''); const [phone, setPhone] = useState('')
  const [area, setArea] = useState(''); const [rooms, setRooms] = useState(''); const [landmark, setLandmark] = useState(false); const [takeaway, setTakeaway] = useState(false)
  const [annual, setAnnual] = useState(''); const [contactId, setContactId] = useState(''); const [meeting, setMeeting] = useState('')
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(true); const [retry, setRetry] = useState(0)
  const applyStatus = (next: QualificationStatus) => { setStatus(next); setContactName(current => current || next.contactName || ''); setArea(next.areaSqm == null ? '' : String(next.areaSqm)); setRooms(next.privateRoomCount == null ? '' : String(next.privateRoomCount)); setLandmark(next.isLandmark); setTakeaway(next.isTakeawayOnly) }
  const refresh = async () => applyStatus(await dataSource.getQualificationStatus(leadId))
  useEffect(() => { let active = true; Promise.all([dataSource.loadCrmEditorOptions(), dataSource.getQualificationStatus(leadId)]).then(([nextOpts, nextStatus]) => { if (!active) return; setOpts(nextOpts); applyStatus(nextStatus); setContactName(nextStatus.contactName || nextOpts.leads.find(x => x.id === leadId)?.contactName || '') }).catch(e => { if (active) setError(e instanceof Error ? e.message : '读取商机资料失败') }).finally(() => { if (active) setBusy(false) }); return () => { active = false } }, [dataSource, leadId, retry])
  const lead = opts?.leads.find(x => x.id === leadId)
  const contacts = opts?.contacts.filter(x => x.isKeyPerson && (x.storeId === lead?.storeId || (!x.storeId && x.brandId === lead?.brandId))) ?? []
  const run = async (operation: () => Promise<unknown>, success: string) => { setBusy(true); setError(''); setNotice(''); try { await operation(); await refresh(); setNotice(success) } catch (e) { setError(e instanceof Error ? e.message : '操作失败') } finally { setBusy(false) } }
  const qualify = async () => { setBusy(true); setError(''); setNotice(''); try { if (!status?.contactabilityReady) { if (!phone.trim()) throw new Error('填写联系电话后即可转商机'); await dataSource.completeLeadContact(leadId, contactName, phone) } await dataSource.qualifyLead(leadId); setNotice('已生成商机，其他资料可继续补充'); await refresh(); await onQualified() } catch (e) { setError(e instanceof Error ? e.message : '转商机失败') } finally { setBusy(false) } }

  if (busy && !opts) return <p className="sw-loading">正在加载线索资料…</p>
  if (error && !opts) return <section className="sw-evidence-editor"><div className="sw-data-error">{error}</div><button className="sw-secondary" onClick={() => setRetry(x => x + 1)}>重试加载</button></section>
  return <section className="sw-evidence-editor">
    <header className="sw-evidence-head"><div><h3>确认联系方式并转商机</h3><p>联系电话是唯一必填项，其他资料均可后补</p></div><strong className={`sw-grade is-${status?.calculatedGrade ?? 'pending'}`}>{status?.calculatedGrade ?? '待完善'}</strong></header>
    <div className="sw-grade-rule"><strong>快速生成商机</strong><span>不会因面积、包厢、关键人或年费事实不完整而拦截</span></div>
    {!status?.opportunityId && <fieldset><legend>联系电话</legend><div className="sw-evidence-grid"><label>联系人（选填）<input value={contactName} onChange={e => setContactName(e.target.value)} placeholder="例如：潘经理" /></label><label>手机号 / 联系电话 *<input value={phone} onChange={e => setPhone(e.target.value)} disabled={status?.contactabilityReady} placeholder={status?.contactabilityReady ? '联系电话已保存' : '填写后即可转商机'} /></label></div><button className="sw-primary" disabled={busy} onClick={() => void qualify()}>{status?.contactabilityReady ? '立即转为商机' : '保存联系电话并转商机'}</button></fieldset>}
    {status?.opportunityId && <div className="sw-success">已生成商机，可进入报价流程；下方资料可继续补充。</div>}
    <details><summary>补充判断资料（可选，不影响转商机）</summary>
      <div className="sw-evidence-progress"><strong>系统辅助判断：{status?.gradeReason || '资料不足时暂按 C 级跟进'}</strong>{status?.missingEvidence.map(item => <span key={item}>○ 建议补充：{item}</span>)}</div>
      <fieldset><legend>门店价值事实</legend><div className="sw-evidence-grid"><label>面积㎡<input type="number" min="0" value={area} onChange={e => setArea(e.target.value)} /></label><label>包厢数<input type="number" min="0" value={rooms} onChange={e => setRooms(e.target.value)} /></label></div><label className="sw-check"><input type="checkbox" checked={landmark} onChange={e => setLandmark(e.target.checked)} />标志性门店</label><label className="sw-check"><input type="checkbox" checked={takeaway} onChange={e => setTakeaway(e.target.checked)} />纯外卖店</label><button className="sw-secondary" disabled={busy} onClick={() => lead?.storeId ? void run(() => dataSource.recordStoreQualificationFacts({ storeId: lead.storeId!, areaSqm: area ? Number(area) : undefined, privateRoomCount: rooms ? Number(rooms) : undefined, isLandmark: landmark, isTakeawayOnly: takeaway }), '门店资料已保存') : setError('尚未关联门店，可先转商机，后续再补')}>保存门店资料</button></fieldset>
      <fieldset><legend>年费沟通事实</legend><label>真实依据<input value={annual} onChange={e => setAnnual(e.target.value)} placeholder="例如：客户接受年费模式并要求下周给方案" /></label><button className="sw-secondary" disabled={busy || status?.annualFeeViable} onClick={() => annual.trim() ? void run(() => dataSource.recordQualificationEvidence({ leadId, evidenceType: 'annual_fee_viable', detail: annual.trim() }), '沟通事实已保存') : setError('请先填写沟通事实')}>{status?.annualFeeViable ? '已记录' : '保存沟通事实'}</button></fieldset>
      <fieldset><legend>关键人信息</legend><label>关键联系人<select value={contactId} onChange={e => setContactId(e.target.value)}><option value="">请选择</option>{contacts.map(x => <option key={x.id} value={x.id}>{x.name} · {x.title}</option>)}</select></label><label>预约时间（不填表示已接触）<input type="datetime-local" value={meeting} onChange={e => setMeeting(e.target.value)} /></label><button className="sw-secondary" disabled={busy || status?.keyPersonReady} onClick={() => contactId ? void run(() => meeting ? dataSource.recordQualificationEvidence({ leadId, evidenceType: 'key_person_meeting_scheduled', detail: '已明确预约关键人', contactId, meetingAt: meeting }) : dataSource.recordQualificationEvidence({ leadId, evidenceType: 'key_person_contacted', detail: '已实际接触关键人', contactId }), '关键人资料已保存') : setError('请先选择关键联系人')}>{status?.keyPersonReady ? '已记录' : '保存关键人资料'}</button></fieldset>
    </details>
    {status?.demoRequiredBeforeDeposit && <div className="sw-demo-gate">A 类商机在确认定金前仍需完成演示。</div>}
    {error && <div className="sw-data-error">{error}</div>}{notice && <div className="sw-success">{notice}</div>}
  </section>
}
