import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'
import type { RealHardwareWorkspace, RealOrderDelivery } from './dataSource'
import { createSupabaseOrderDeliveryDataSource } from './supabaseDataSource'

const dataSource = createSupabaseOrderDeliveryDataSource(supabase)
const requestedOrderId = new URLSearchParams(window.location.hash.split('?')[1] ?? '').get('order') ?? ''

export default function OrderDeliveryRealRoute() {
  const [orders, setOrders] = useState<RealOrderDelivery[]>([]); const [selected, setSelected] = useState<RealOrderDelivery | null>(null)
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  const [hardware, setHardware] = useState<RealHardwareWorkspace | null>(null); const [stockId, setStockId] = useState(''); const [stockQuantity, setStockQuantity] = useState('1'); const [expectedOn, setExpectedOn] = useState('')
  const load = useCallback(async () => { setBusy(true); setError(null); try { const rows = await dataSource.listOrders(); setOrders(rows); setSelected(current => current ? rows.find(x => x.orderId === current.orderId) ?? null : rows.find(x => x.orderId === requestedOrderId) ?? null) } catch (caught) { setError(caught instanceof Error ? caught.message : '读取真实订单履约失败') } finally { setBusy(false) } }, [])
  const loadHardware = useCallback(async (deliveryId: string) => { try { const workspace = await dataSource.loadHardwareWorkspace(deliveryId); setHardware(workspace); setStockId(current => current || workspace.stocks[0]?.id || '') } catch (caught) { setHardware(null); setError(caught instanceof Error ? caught.message : '读取硬件库存失败') } }, [])
  useEffect(() => { queueMicrotask(() => { void load() }) }, [load])
  useEffect(() => { queueMicrotask(() => { if (selected?.deliveryId) void loadHardware(selected.deliveryId); else setHardware(null) }) }, [selected?.deliveryId, loadHardware])
  const run = async (label: string, operation: () => Promise<void>) => { setBusy(true); setError(null); setNotice(null); try { await operation(); setNotice(`${label}成功`); await load(); if (selected?.deliveryId) await loadHardware(selected.deliveryId) } catch (caught) { setError(caught instanceof Error ? caught.message : `${label}失败`) } finally { setBusy(false) } }
  const d = selected
  return <section className="min-h-screen bg-slate-50 p-4 md:p-6"><header className="mb-5"><p className="text-sm font-medium text-indigo-600">真实数据入口</p><h1 className="text-2xl font-bold text-slate-900">订单履约工作台</h1><p className="mt-1 text-sm text-slate-500">状态与库存只能由服务器RPC推进；失败不会回退演示数据。</p></header>
    {error && <p role="alert" className="mb-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p role="status" className="mb-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    {busy && orders.length === 0 && <p className="text-sm text-slate-500">正在加载可见订单…</p>} {!busy && !error && orders.length === 0 && <p className="rounded-lg border border-dashed p-5 text-sm text-slate-500">当前账号没有可见订单</p>}
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{orders.map(item => <button key={item.orderId} onClick={() => { setSelected(item); setError(null); setNotice(null) }} className={`rounded-xl border bg-white p-4 text-left ${d?.orderId === item.orderId ? 'border-indigo-500' : 'border-slate-200'}`}><strong>{item.brandName ? `${item.brandName} · ` : ''}{item.storeName}</strong><span className="mt-1 block text-sm text-slate-500">订单：{item.orderStatus} · 交付：{item.deliveryStatus ?? '未建立'}</span><span className="block text-sm text-slate-500">软件 {item.state?.softwareStatus ?? '-'} · 硬件 {item.state?.hardwareStatus ?? '-'}</span></button>)}</div>
    {d && <div className="mt-4 max-w-4xl rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">{d.storeName} 履约详情</h2><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p>安装：{d.installedAt ? '已完成' : '未完成'}</p><p>培训：{d.trainedAt ? '已完成' : '未完成'}</p><p>售后交接：{d.handoffStatus ?? '未创建'}</p><p>服务到期：{d.serviceExpiresOn ?? '未设置'}</p></div>
      {d.exceptions.filter(x => x.status === 'open').map((x, i) => <p key={i} className="mt-2 rounded-lg bg-red-50 p-2 text-sm text-red-700">异常：{x.details} · 预计解决 {x.expectedResolutionOn ?? '待确认'}</p>)}
      <div className="mt-3 flex flex-wrap gap-2">{!d.deliveryId && <button disabled={busy || !d.storeId} onClick={() => run('建立交付', () => dataSource.createDelivery(d.orderId, d.storeId, null))} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50">RPC建立交付</button>}{d.deliveryId && <><button disabled={busy} onClick={() => run('软件开通', () => dataSource.activateSoftware(d.deliveryId!))} className="rounded-lg border px-3 py-2 text-sm">RPC软件开通</button>{hardware?.canManage && <button disabled={busy} onClick={() => run('硬件完成', () => dataSource.completeHardware(d.deliveryId!))} className="rounded-lg border px-3 py-2 text-sm">RPC硬件完成</button>}<button disabled={busy} onClick={() => run('安装确认', () => dataSource.markImplementation(d.deliveryId!, 'installation'))} className="rounded-lg border px-3 py-2 text-sm">RPC完成安装</button><button disabled={busy} onClick={() => run('培训确认', () => dataSource.markImplementation(d.deliveryId!, 'training'))} className="rounded-lg border px-3 py-2 text-sm">RPC完成培训</button><button disabled={busy} onClick={() => run('创建交接', () => dataSource.createHandoff(d.deliveryId!))} className="rounded-lg border px-3 py-2 text-sm">RPC创建交接</button>{d.handoffId && <button disabled={busy} onClick={() => run('运维接手', () => dataSource.confirmHandoff(d.handoffId!))} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white">RPC运维确认</button>}</>}</div>
      {d.deliveryId && hardware && <div className="mt-4 border-t pt-4"><h3 className="text-sm font-semibold">硬件库存与出库</h3>{!hardware.canManage && <p className="mt-2 text-sm text-slate-500">当前为只读视图；库存操作仅仓库、财务或已授权角色可用。</p>}{hardware.canManage && <><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_100px_150px_auto]"><select aria-label="库存硬件" value={stockId} onChange={event => setStockId(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">选择硬件</option>{hardware.stocks.map(stock => <option key={stock.id} value={stock.id}>{stock.name}（可用 {stock.availableQuantity}）</option>)}</select><input aria-label="预留数量" type="number" min="1" step="1" value={stockQuantity} onChange={event => setStockQuantity(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"/><input aria-label="预计到货日" type="date" min={new Date().toISOString().slice(0, 10)} required value={expectedOn} onChange={event => setExpectedOn(event.target.value)} className="rounded-lg border px-3 py-2 text-sm"/><button disabled={busy || !stockId || Number(stockQuantity) <= 0 || !expectedOn} onClick={() => run('库存预留', () => dataSource.reserveStock(d.deliveryId!, stockId, Number(stockQuantity), expectedOn || null))} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white disabled:opacity-50">预留库存</button></div><div className="mt-3 grid gap-2">{hardware.reservations.length === 0 && <p className="text-sm text-slate-500">暂无预留记录</p>}{hardware.reservations.map(reservation => <div key={reservation.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{reservation.itemName} × {reservation.quantity} · {reservation.status}</span>{reservation.status === 'reserved' && <button disabled={busy} onClick={() => run('硬件出库', () => dataSource.shipStock(reservation.id))} className="rounded-lg border border-indigo-300 px-3 py-1 text-indigo-700">确认出库</button>}</div>)}</div></>}</div>}
      {d.renewals.length > 0 && <div className="mt-4 border-t pt-3"><h3 className="text-sm font-semibold">续费节点</h3><div className="mt-2 flex flex-wrap gap-2">{d.renewals.map(x => <span key={x.daysBefore} className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-800">提前{x.daysBefore}天 · {x.dueOn} · {x.status}</span>)}</div></div>}
    </div>}
  </section>
}
