export { ManagementBoardDemo as default, ManagementBoardDemo } from './ManagementBoardDemo'
export { managementBoardDemoItems } from './demoData'
export { filterBoardItems, handleLocally, isClosingWithinSevenDays, isSalesMeetingItem } from './workflow'
export type { BoardFilter, BoardItemStatus, ExceptionType, ManagementBoardItem } from './types'
export { ManagementBoardDataError } from './dataSource'
export type { ManagementBoardDataSource, SupervisorExceptionRecord } from './dataSource'
export { createSupabaseManagementBoardDataSource } from './supabaseDataSource'
