import { useCallback, useEffect, useState } from 'react'
import type { ManagementBoardDataSource, PerformanceRecord, ProfitSummaryRecord, ReconciliationBatchRecord, SupervisorMarginRecord } from './dataSource'

type Tab = 'targets' | 'reconciliation' | 'profit'
type DraftLine = { profile_id: string; order_id: string; official_points: number; gmv_type: 'new' | 'renewal'; gmv_amount: number; observed_month: string }
const money = (value: number) => `¥${value.toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const quarterOf = (date = new Date()) => `${date.getFullYear()}-${String(Math.floor(date.getMonth() / 3) * 3 + 1).padStart(2, '0')}-01`
const monthOf = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-01`

export function ManagementOperationsPanels({ dataSource }: { dataSource: ManagementBoardDataSource }) {
  const [tab, setTab] = useState<Tab>('targets')
  const [quarter, setQuarter] = useState(quarterOf)
  const [performance, setPerformance] = useState<PerformanceRecord[]>([])
  const [batches, setBatches] = useState<ReconciliationBatchRecord[]>([])
  const [profits, setProfits] = useState<ProfitSummaryRecord[]>([])
  const [margins, setMargins] = useState<SupervisorMarginRecord[]>([])
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)

  const load = useCallback(async () => {
    setBusy(true); setError(null)
    const [p, b, f, m] = await Promise.allSettled([dataSource.listPerformance(quarter), dataSource.listReconciliations(), dataSource.listProfitSummary(), dataSource.listSupervisorMargins()])
    if (p.status === 'fulfilled') setPerformance(p.value); else setError(p.reason instanceof Error ? p.reason.message : '读取管理数据失败')
    setBatches(b.status === 'fulfilled' ? b.value : []); setProfits(f.status === 'fulfilled' ? f.value : []); setMargins(m.status === 'fulfilled' ? m.value : []); setBusy(false)
  }, [dataSource, quarter])
  useEffect(() => { queueMicrotask(() => { void load() }) }, [load])
  const run = async (label: string, action: () => Promise<void>) => { setBusy(true); setError(null); setNotice(null); try { await action(); setNotice(`${label}已完成`); await load(); return true } catch (caught) { setError(caught instanceof Error ? caught.message : `${label}失败`); return false } finally { setBusy(false) } }

  return <section className="mt-6 rounded-2xl border bg-white p-4 shadow-sm md:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium text-indigo-600">管理与经营</p><h2 className="text-xl font-bold text-slate-900">目标、官方对账与双账本</h2></div><input aria-label="季度开始月" type="month" value={quarter.slice(0, 7)} onChange={event => { const date = new Date(`${event.target.value}-01T00:00:00`); setQuarter(quarterOf(date)) }} className="rounded-lg border px-3 py-2 text-sm"/></div>
    <div className="mt-4 flex gap-2 overflow-x-auto">{([['targets','季度目标 / 月观察'],['reconciliation','官方对账'],['profit','双账本利润']] as Array<[Tab,string]>).map(([key,label]) => <button key={key} onClick={() => setTab(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm ${tab === key ? 'bg-indigo-600 text-white' : 'border text-slate-700'}`}>{label}</button>)}</div>
    {error && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p role="status" className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    {tab === 'targets' && <TargetsPanel rows={performance} margins={margins} quarter={quarter} busy={busy} run={run} dataSource={dataSource}/>} 
    {tab === 'reconciliation' && <ReconciliationPanel rows={performance} batches={batches} quarter={quarter} busy={busy} run={run} dataSource={dataSource}/>} 
    {tab === 'profit' && <ProfitPanel rows={profits} busy={busy} run={run} dataSource={dataSource}/>} 
  </section>
}

function TargetsPanel({ rows, margins, quarter, busy, run, dataSource }: { rows: PerformanceRecord[]; margins: SupervisorMarginRecord[]; quarter: string; busy: boolean; run: (label: string, action: () => Promise<void>) => Promise<boolean>; dataSource: ManagementBoardDataSource }) {
  const editable = rows.find(row => row.canSetTarget)
  const [profileId, setProfileId] = useState(editable?.profileId ?? '')
  const selected = rows.find(row => row.profileId === profileId) ?? editable
  const [points, setPoints] = useState(''); const [newTarget, setNewTarget] = useState(''); const [renewalTarget, setRenewalTarget] = useState('')
  const [estimated, setEstimated] = useState(''); const [newGmv, setNewGmv] = useState(''); const [renewalGmv, setRenewalGmv] = useState('')
  useEffect(() => { queueMicrotask(() => { setProfileId(current => rows.some(row => row.profileId === current && row.canSetTarget) ? current : editable?.profileId ?? '') }) }, [editable?.profileId, rows])
  useEffect(() => { queueMicrotask(() => { setPoints(selected ? String(selected.pointsTarget) : ''); setNewTarget(selected ? String(selected.newGmvTarget) : ''); setRenewalTarget(selected ? String(selected.renewalGmvTarget) : '') }) }, [selected])
  if (rows.length === 0) return <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">请先给成员分配销售岗位</p>
  return <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,0.6fr)]"><div><div className="grid gap-3 sm:grid-cols-2">{rows.map(row => <article key={row.profileId} className="rounded-xl border p-4"><div className="flex justify-between"><b>{row.profileName}</b><span className="text-xs text-slate-500">{row.quarterStart}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Metric label="预计 / 官方积分" value={`${row.estimatedPoints} / ${row.officialPoints}`}/><Metric label="积分目标" value={String(row.pointsTarget)}/><Metric label="新签 GMV" value={`${money(row.newGmvActual)} / ${money(row.newGmvTarget)}`}/><Metric label="续费 GMV" value={`${money(row.renewalGmvActual)} / ${money(row.renewalGmvTarget)}`}/></div><div className="mt-3 flex gap-2 overflow-x-auto">{row.monthlyObservations.map(month => <div key={month.monthStart} className="min-w-32 rounded-lg bg-slate-50 p-2 text-xs"><b>{month.monthStart.slice(5,7)}月</b><p>预计/官方：{month.estimatedPoints}/{month.officialPoints}</p><p>新签：{money(month.newGmv)}</p><p>续费：{money(month.renewalGmv)}</p></div>)}</div></article>)}</div>{margins.length > 0 && <div className="mt-4 rounded-xl border p-4"><h3 className="font-semibold">下属订单价差</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{margins.map(item => <div key={item.orderId} className="rounded-lg bg-slate-50 p-2 text-sm"><b>{item.ownerName} · {item.orderNumber}</b><span className="float-right text-indigo-700">{money(item.salesMargin)}</span></div>)}</div></div>}</div>
    <aside className="space-y-3"><div className="rounded-xl border p-4"><h3 className="font-semibold">设置季度目标</h3><select value={profileId} onChange={event => setProfileId(event.target.value)} className="mt-3 w-full rounded-lg border px-3 py-2 text-sm">{rows.filter(row => row.canSetTarget).map(row => <option key={row.profileId} value={row.profileId}>{row.profileName}</option>)}</select><NumberField label="积分目标" value={points} setValue={setPoints}/><NumberField label="新签 GMV 目标" value={newTarget} setValue={setNewTarget}/><NumberField label="续费 GMV 目标" value={renewalTarget} setValue={setRenewalTarget}/><button disabled={busy || !selected} onClick={() => selected && void run('季度目标', () => dataSource.setQuarterTarget({ profileId: selected.profileId, quarterStart: quarter, pointsTarget: Number(points), newGmvTarget: Number(newTarget), renewalGmvTarget: Number(renewalTarget) }))} className="mt-3 w-full rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white disabled:opacity-40">保存目标</button></div>
    <div className="rounded-xl border p-4"><h3 className="font-semibold">我的本月观察</h3><NumberField label="预计积分" value={estimated} setValue={setEstimated}/><NumberField label="新签 GMV" value={newGmv} setValue={setNewGmv}/><NumberField label="续费 GMV" value={renewalGmv} setValue={setRenewalGmv}/><button disabled={busy} onClick={() => void run('月观察', () => dataSource.saveMonthlyObservation({ monthStart: monthOf(), estimatedPoints: Number(estimated), newGmv: Number(newGmv), renewalGmv: Number(renewalGmv), idempotencyKey: crypto.randomUUID() }))} className="mt-3 w-full rounded-lg border border-indigo-300 px-3 py-2 text-sm text-indigo-700 disabled:opacity-40">保存月观察</button></div></aside></div>
}

function ReconciliationPanel({ rows, batches, quarter, busy, run, dataSource }: { rows: PerformanceRecord[]; batches: ReconciliationBatchRecord[]; quarter: string; busy: boolean; run: (label: string, action: () => Promise<void>) => Promise<boolean>; dataSource: ManagementBoardDataSource }) {
  const [sourceRef, setSourceRef] = useState(''); const [profileId, setProfileId] = useState(''); const [orderId, setOrderId] = useState(''); const [officialPoints, setOfficialPoints] = useState('0'); const [gmvType, setGmvType] = useState<'new'|'renewal'>('new'); const [gmvAmount, setGmvAmount] = useState('0'); const [observedMonth, setObservedMonth] = useState(monthOf); const [lines, setLines] = useState<DraftLine[]>([])
  useEffect(() => { queueMicrotask(() => { setObservedMonth(quarter); setLines([]) }) }, [quarter])
  const addLine = () => { if (!profileId) return; setLines(current => [...current, { profile_id: profileId, order_id: orderId, official_points: Number(officialPoints), gmv_type: gmvType, gmv_amount: Number(gmvAmount), observed_month: `${observedMonth.slice(0,7)}-01` }]); setOrderId('') }
  return <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><h3 className="font-semibold">导入官方对账</h3><input value={sourceRef} onChange={event => setSourceRef(event.target.value)} placeholder="对账单号 / 文件名" className="mt-3 w-full rounded-lg border px-3 py-2 text-sm"/><select value={profileId} onChange={event => setProfileId(event.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2 text-sm"><option value="">选择销售</option>{rows.map(row => <option key={row.profileId} value={row.profileId}>{row.profileName}</option>)}</select><input value={orderId} onChange={event => setOrderId(event.target.value)} placeholder="订单ID（续费可选）" className="mt-2 w-full rounded-lg border px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-2"><NumberField label="官方积分" value={officialPoints} setValue={setOfficialPoints}/><NumberField label="GMV" value={gmvAmount} setValue={setGmvAmount}/></div><div className="mt-2 grid grid-cols-2 gap-2"><select value={gmvType} onChange={event => setGmvType(event.target.value as 'new'|'renewal')} className="rounded-lg border px-3 py-2 text-sm"><option value="new">新签</option><option value="renewal">续费</option></select><input type="month" value={observedMonth.slice(0,7)} onChange={event => setObservedMonth(`${event.target.value}-01`)} className="rounded-lg border px-3 py-2 text-sm"/></div><button onClick={addLine} className="mt-2 w-full rounded-lg border px-3 py-2 text-sm">加入导入清单（{lines.length}）</button><button disabled={busy || !sourceRef.trim() || !lines.length} onClick={() => void run('官方对账导入', async () => { await dataSource.createReconciliation({ quarterStart: quarter, sourceRef: sourceRef.trim(), lines }); setLines([]); setSourceRef('') })} className="mt-2 w-full rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white disabled:opacity-40">创建待确认批次</button></div>
    <div className="rounded-xl border p-4"><h3 className="font-semibold">对账批次</h3><div className="mt-3 space-y-2">{batches.map(batch => <div key={batch.batchId} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-3 text-sm"><span><b>{batch.sourceRef}</b><small className="block text-slate-500">{batch.quarterStart} · {batch.lineCount}条</small></span>{batch.status === 'draft' ? <button disabled={busy} onClick={() => void run('官方对账确认', () => dataSource.confirmReconciliation(batch.batchId))} className="rounded-lg bg-indigo-600 px-3 py-2 text-white">确认</button> : <span className="text-emerald-700">已确认</span>}</div>)}{!batches.length && <p className="text-sm text-slate-500">当前账号无财务对账权限或暂无批次。</p>}</div></div></div>
}

function ProfitPanel({ rows, busy, run, dataSource }: { rows: ProfitSummaryRecord[]; busy: boolean; run: (label: string, action: () => Promise<void>) => Promise<boolean>; dataSource: ManagementBoardDataSource }) {
  const [type, setType] = useState<'quarterly_rebate'|'expense'>('quarterly_rebate'); const [amount, setAmount] = useState(''); const [effectiveOn, setEffectiveOn] = useState(new Date().toLocaleDateString('en-CA')); const [reason, setReason] = useState('')
  const canDetail = rows.some(row => row.canViewDetails)
  return <div className="mt-4"><div className="grid gap-3 md:grid-cols-2">{rows.map(row => <article key={row.quarterStart} className="rounded-xl border p-4"><div className="flex justify-between"><b>{row.quarterStart}</b><span className="text-xs text-slate-500">预测 / 实际分开</span></div><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="预测利润" value={money(row.forecastProfit)}/><Metric label="实际利润" value={money(row.actualProfit)}/></div>{row.canViewDetails && <div className="mt-3 grid grid-cols-2 gap-1 text-xs text-slate-600"><span>实收 {money(row.actualReceipts)}</span><span>退款冲销 -{money(row.refundReversals)}</span><span>采购 -{money(row.procurementPayments)}</span><span>费用 -{money(row.salesExpenses + row.companyExpenses)}</span><span>季度返利 +{money(row.quarterlyRebates)}</span></div>}{!row.canViewDetails && <p className="mt-3 text-xs text-slate-500">老板汇总视图：不显示原始财务明细。</p>}</article>)}</div>{!rows.length && <p className="rounded-xl border border-dashed p-5 text-sm text-slate-500">当前账号无公司利润查看权限或暂无数据。</p>}
    {canDetail && <div className="mt-4 max-w-xl rounded-xl border p-4"><h3 className="font-semibold">追加季度返利 / 费用</h3><select value={type} onChange={event => setType(event.target.value as 'quarterly_rebate'|'expense')} className="mt-3 w-full rounded-lg border px-3 py-2 text-sm"><option value="quarterly_rebate">季度返利</option><option value="expense">公司费用</option></select><NumberField label="金额" value={amount} setValue={setAmount}/><input type="date" value={effectiveOn} onChange={event => setEffectiveOn(event.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2 text-sm"/><textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="原因 / 凭证说明" className="mt-2 min-h-16 w-full rounded-lg border px-3 py-2 text-sm"/><button disabled={busy || !(Number(amount)>0) || !reason.trim()} onClick={() => void run('利润调整', () => dataSource.addProfitAdjustment({ type, amount: Number(amount), effectiveOn, reason: reason.trim(), idempotencyKey: crypto.randomUUID() }))} className="mt-2 w-full rounded-lg bg-indigo-600 px-3 py-2 text-sm text-white disabled:opacity-40">追加记录</button></div>}
  </div>
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-2 text-sm"><span className="block text-xs text-slate-500">{label}</span><b>{value}</b></div> }
function NumberField({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { return <label className="mt-2 block text-xs text-slate-600">{label}<input type="number" min="0" step="0.01" value={value} onChange={event => setValue(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label> }
