import { useEffect, useState } from 'react'
import type { CommerceData } from './domain/commerce'
import type { AuthenticatedWorkspace } from './lib/access'
import { SupabaseCommerceReader } from './lib/supabase-commerce-reader'
import { EmptyState, StatusBadge } from './ui'
const reader = new SupabaseCommerceReader()
function useCommerce(user: AuthenticatedWorkspace, allowed: boolean) { const [data, setData] = useState<CommerceData>(); const [error, setError] = useState(false); useEffect(() => { if (!allowed) return; const controller = new AbortController(); reader.load(user.companyId, controller.signal).then(setData).catch(() => { if (!controller.signal.aborted) setError(true) }); return () => controller.abort() }, [allowed, user.companyId]); return { data, error } }
export function CatalogPage({ user }: { user: AuthenticatedWorkspace }) { const allowed = user.primaryRole === 'sales' || user.primaryRole === 'admin', state = useCommerce(user, allowed); if (!allowed) return <section className="workspace access-denied" data-testid="catalog-denied"><h1>无权访问产品目录</h1></section>; if (state.error) return <section className="workspace" data-testid="catalog-error"><StatusBadge tone="danger">产品读取失败</StatusBadge></section>; if (!state.data) return <section className="workspace" data-testid="catalog-loading"><StatusBadge tone="info">正在读取产品…</StatusBadge></section>; return <section className="workspace" data-testid="catalog-page"><h1>产品目录</h1>{!state.data.products.length ? <EmptyState title="当前没有产品" description="这里仅显示真实产品数据。" /> : <ol className="work-item-list">{state.data.products.map((item) => <li key={item.id} data-testid="product-row"><strong>{item.name}</strong><StatusBadge tone={item.isActive ? 'success' : 'neutral'}>{item.productType}</StatusBadge></li>)}</ol>}</section> }
export function OrdersPage({ user }: { user: AuthenticatedWorkspace }) { const allowed = user.primaryRole === 'sales' || user.primaryRole === 'admin', state = useCommerce(user, allowed); if (!allowed) return <section className="workspace access-denied" data-testid="orders-denied"><h1>当前岗位尚未获得订单分配视图</h1></section>; if (state.error) return <section className="workspace" data-testid="orders-error"><StatusBadge tone="danger">订单读取失败</StatusBadge></section>; if (!state.data) return <section className="workspace" data-testid="orders-loading"><StatusBadge tone="info">正在读取订单…</StatusBadge></section>; return <section className="workspace" data-testid="orders-page"><h1>报价与订单</h1>{!state.data.quotes.length && !state.data.orders.length ? <EmptyState title="当前没有报价或订单" description="这里仅显示真实报价和订单数据。" /> : <><h2>报价</h2><ol className="work-item-list">{state.data.quotes.map((item) => <li key={item.id} data-testid="quote-row"><strong>{item.id}</strong><StatusBadge>{item.status}</StatusBadge></li>)}</ol><h2>订单</h2><ol className="work-item-list">{state.data.orders.map((item) => <li key={item.id} data-testid="order-row"><strong>{item.id}</strong><StatusBadge tone="info">{item.status}</StatusBadge></li>)}</ol></>}</section> }
