import { useEffect, useState } from 'react'
import type { FulfillmentData } from './domain/fulfillment'
import type { AuthenticatedWorkspace } from './lib/access'
import { SupabaseFulfillmentReader } from './lib/supabase-fulfillment-reader'
import { EmptyState, StatusBadge } from './ui'
const reader = new SupabaseFulfillmentReader()
function useData(user: AuthenticatedWorkspace, allowed: boolean) { const [data, setData] = useState<FulfillmentData>(); const [error, setError] = useState(false); useEffect(() => { if (!allowed) return; const controller = new AbortController(); reader.load(user.companyId, controller.signal).then(setData).catch(() => { if (!controller.signal.aborted) setError(true) }); return () => controller.abort() }, [allowed, user.companyId]); return { data, error } }
export function WarehousePage({ user }: { user: AuthenticatedWorkspace }) { const allowed = user.primaryRole === 'admin', state = useData(user, allowed); if (!allowed) return <section className="workspace access-denied" data-testid="warehouse-denied"><h1>当前账号没有仓库职能</h1></section>; if (state.error) return <section className="workspace" data-testid="warehouse-error"><StatusBadge tone="danger">库存读取失败</StatusBadge></section>; if (!state.data) return <section className="workspace" data-testid="warehouse-loading"><StatusBadge tone="info">正在读取库存…</StatusBadge></section>; return <section className="workspace" data-testid="warehouse-page"><h1>仓库处理</h1>{!state.data.stock.length ? <EmptyState title="当前没有库存记录" description="这里仅显示真实库存。" /> : <ol className="work-item-list">{state.data.stock.map((item) => <li key={item.id} data-testid="warehouse-row"><div><strong>{item.productId}</strong><span>仓库 {item.warehouseId}</span></div><StatusBadge>可用 {item.onHandQuantity - item.reservedQuantity}</StatusBadge><small>已预留 {item.reservedQuantity}</small></li>)}</ol>}</section> }
export function FulfillmentPage({ user }: { user: AuthenticatedWorkspace }) { const allowed = ['implementation', 'operations', 'admin'].includes(user.primaryRole), state = useData(user, allowed); if (!allowed) return <section className="workspace access-denied" data-testid="fulfillment-denied"><h1>无权访问履约任务</h1></section>; if (state.error) return <section className="workspace" data-testid="fulfillment-error"><StatusBadge tone="danger">履约读取失败</StatusBadge></section>; if (!state.data) return <section className="workspace" data-testid="fulfillment-loading"><StatusBadge tone="info">正在读取履约任务…</StatusBadge></section>; const jobs = user.primaryRole === 'admin' ? state.data.jobs : state.data.jobs.filter((item) => item.assigneeId === user.userId); return <section className="workspace" data-testid="fulfillment-page"><h1>实施与服务履约</h1>{!jobs.length ? <EmptyState title="当前没有本人履约任务" description="这里仅显示真实分配结果。" /> : <ol className="work-item-list">{jobs.map((item) => <li key={item.id} data-testid="fulfillment-row"><div><strong>门店 {item.storeId}</strong><span>订单行 {item.orderLineId}</span></div><StatusBadge tone="info">{item.status}</StatusBadge></li>)}</ol>}</section> }
