import type { FulfillmentData, FulfillmentJob, ServiceAssignment, ServiceType, WarehouseStock } from '../domain/fulfillment'
import { getGreenfieldSupabase } from './supabase'
const obj = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('FULFILLMENT_ROW_INVALID'); return v as Record<string, unknown> }
const text = (r: Record<string, unknown>, k: string) => { const v = r[k]; if (typeof v !== 'string' || !v.trim()) throw new Error(`FULFILLMENT_FIELD_INVALID:${k}`); return v }
const number = (r: Record<string, unknown>, k: string) => { const raw = r[k], value = typeof raw === 'string' ? Number(raw) : raw; if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) throw new Error(`FULFILLMENT_FIELD_INVALID:${k}`); return value }
const stock = (v: unknown): WarehouseStock => { const r = obj(v); return Object.freeze({ id: text(r, 'id'), companyId: text(r, 'company_id'), warehouseId: text(r, 'warehouse_id'), productId: text(r, 'product_id'), onHandQuantity: number(r, 'on_hand_quantity'), reservedQuantity: number(r, 'reserved_quantity') }) }
const job = (v: unknown): FulfillmentJob => { const r = obj(v), status = text(r, 'status'), assigned = r.assigned_to; if (!['pending', 'reserved', 'scheduled', 'in_progress', 'completed', 'cancelled'].includes(status)) throw new Error('FULFILLMENT_FIELD_INVALID:status'); if (assigned !== null && (typeof assigned !== 'string' || !assigned.trim())) throw new Error('FULFILLMENT_FIELD_INVALID:assigned_to'); return Object.freeze({ id: text(r, 'id'), companyId: text(r, 'company_id'), storeId: text(r, 'store_id'), orderLineId: text(r, 'order_line_id'), assigneeId: assigned as string | null, status: status as FulfillmentJob['status'] }) }
const nullableDate = (r: Record<string, unknown>, k: string) => { const v = r[k]; if (v === null) return null; if (typeof v !== 'string' || Number.isNaN(Date.parse(v))) throw new Error(`FULFILLMENT_FIELD_INVALID:${k}`); return v }
const assignment = (v: unknown): ServiceAssignment => { const r = obj(v), serviceType = text(r, 'service_type'), status = text(r, 'status'); if (!['installation', 'training', 'acceptance', 'operations_handoff'].includes(serviceType)) throw new Error('FULFILLMENT_FIELD_INVALID:service_type'); if (!['assigned', 'in_progress', 'completed', 'cancelled'].includes(status)) throw new Error('FULFILLMENT_FIELD_INVALID:assignment_status'); return Object.freeze({ id: text(r, 'id'), companyId: text(r, 'company_id'), fulfillmentUnitId: text(r, 'fulfillment_unit_id'), assigneeId: text(r, 'assignee_id'), serviceType: serviceType as ServiceType, status: status as ServiceAssignment['status'], scheduledAt: nullableDate(r, 'scheduled_at'), completedAt: nullableDate(r, 'completed_at') }) }
export class SupabaseFulfillmentReader { async load(companyId: string, signal?: AbortSignal): Promise<FulfillmentData> { const c = getGreenfieldSupabase(); const q = (table: string, fields: string) => { let request = c.from(table).select(fields).eq('company_id', companyId); if (signal) request = request.abortSignal(signal); return request }; const [stockResult, jobResult, assignmentResult] = await Promise.all([q('stock_items', 'id,company_id,warehouse_id,product_id,on_hand_quantity,reserved_quantity'), q('fulfillment_units', 'id,company_id,store_id,order_line_id,assigned_to,status'), q('service_assignments', 'id,company_id,fulfillment_unit_id,assignee_id,service_type,status,scheduled_at,completed_at')]); const error = stockResult.error ?? jobResult.error ?? assignmentResult.error; if (error) throw new Error(`FULFILLMENT_QUERY_FAILED:${error.code ?? 'UNKNOWN'}`); return Object.freeze({ stock: Object.freeze((stockResult.data ?? []).map(stock)), jobs: Object.freeze((jobResult.data ?? []).map(job)), assignments: Object.freeze((assignmentResult.data ?? []).map(assignment)) }) } }
