import type { Lead, LeadPoolStatus, Opportunity, OpportunityStage, SalesPipeline } from '../domain/sales-pipeline'
import { getGreenfieldSupabase } from './supabase'
const LEAD = new Set<LeadPoolStatus>(['public_pool', 'claimed', 'converted', 'discarded']); const STAGE = new Set<OpportunityStage>(['discovery', 'qualified', 'proposal', 'negotiation', 'won', 'lost'])
const row = (value: unknown): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('SALES_ROW_INVALID'); return value as Record<string, unknown> }
const text = (value: Record<string, unknown>, key: string) => { const field = value[key]; if (typeof field !== 'string' || !field.trim()) throw new Error(`SALES_FIELD_INVALID:${key}`); return field }
const optionalText = (value: Record<string, unknown>, key: string) => value[key] === null ? null : text(value, key)
const time = (value: Record<string, unknown>, key: string) => { const field = text(value, key); if (!Number.isFinite(Date.parse(field))) throw new Error(`SALES_FIELD_INVALID:${key}`); return field }
const optionalTime = (value: Record<string, unknown>, key: string) => { const field = optionalText(value, key); if (field !== null && !Number.isFinite(Date.parse(field))) throw new Error(`SALES_FIELD_INVALID:${key}`); return field }
const mapLead = (value: unknown): Lead => { const item = row(value), poolStatus = text(item, 'pool_status'); if (!LEAD.has(poolStatus as LeadPoolStatus)) throw new Error('SALES_FIELD_INVALID:pool_status'); return Object.freeze({ id: text(item, 'id'), companyId: text(item, 'company_id'), ownerId: optionalText(item, 'owner_id'), name: text(item, 'name'), region: text(item, 'region'), poolStatus: poolStatus as LeadPoolStatus, cleanupDueAt: optionalTime(item, 'cleanup_due_at'), createdAt: time(item, 'created_at') }) }
const mapOpportunity = (value: unknown): Opportunity => { const item = row(value), stage = text(item, 'stage'); if (!STAGE.has(stage as OpportunityStage)) throw new Error('SALES_FIELD_INVALID:stage'); return Object.freeze({ id: text(item, 'id'), companyId: text(item, 'company_id'), ownerId: text(item, 'owner_id'), customerId: text(item, 'customer_id'), storeId: text(item, 'store_id'), name: text(item, 'name'), stage: stage as OpportunityStage }) }
export class SupabaseSalesPipelineReader { async load(companyId: string, ownerId: string, includeCompany: boolean, signal?: AbortSignal): Promise<SalesPipeline> { const client = getGreenfieldSupabase(); let leads = client.from('leads').select('id,company_id,owner_id,name,region,pool_status,cleanup_due_at,created_at').eq('company_id', companyId); let opportunities = client.from('opportunities').select('id,company_id,owner_id,customer_id,store_id,name,stage').eq('company_id', companyId); if (!includeCompany) opportunities = opportunities.eq('owner_id', ownerId); if (signal) { leads = leads.abortSignal(signal); opportunities = opportunities.abortSignal(signal) } const [leadResult, opportunityResult] = await Promise.all([leads, opportunities]); const failure = leadResult.error ?? opportunityResult.error; if (failure) throw new Error(`SALES_PIPELINE_QUERY_FAILED:${failure.code ?? 'UNKNOWN'}`); return Object.freeze({ leads: Object.freeze((leadResult.data ?? []).map(mapLead)), opportunities: Object.freeze((opportunityResult.data ?? []).map(mapOpportunity)) }) } }
