import type { FinanceData, InternalPaymentEvent, LaborEarning, PaymentEvent, ProfitEntry, RefundEvent } from '../domain/finance'
import { getGreenfieldSupabase } from './supabase'
const obj = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('FINANCE_ROW_INVALID'); return v as Record<string, unknown> }
const text = (r: Record<string, unknown>, k: string) => { const v = r[k]; if (typeof v !== 'string' || !v.trim()) throw new Error(`FINANCE_FIELD_INVALID:${k}`); return v }
const money = (r: Record<string, unknown>, k: string) => { const raw = r[k], value = typeof raw === 'string' ? Number(raw) : raw; if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) throw new Error(`FINANCE_FIELD_INVALID:${k}`); return value }
const eventType = (r: Record<string, unknown>, k: string, first: string) => { const value = text(r, k); if (value !== first && value !== 'reversed') throw new Error(`FINANCE_FIELD_INVALID:${k}`); return value }
const payment = (v: unknown): PaymentEvent => { const r = obj(v); return Object.freeze({ id: String(r.id), companyId: text(r, 'company_id'), orderId: text(r, 'order_id'), eventType: eventType(r, 'event_type', 'confirmed') as PaymentEvent['eventType'], amount: money(r, 'payment_amount') }) }
const internal = (v: unknown): InternalPaymentEvent => { const r = obj(v); return Object.freeze({ id: String(r.id), companyId: text(r, 'company_id'), orderId: text(r, 'order_id'), eventType: eventType(r, 'event_type', 'confirmed') as InternalPaymentEvent['eventType'], amount: money(r, 'internal_payment_amount') }) }
const profit = (v: unknown): ProfitEntry => { const r = obj(v), beneficiary = r.beneficiary_user_id; if (beneficiary !== null && (typeof beneficiary !== 'string' || !beneficiary.trim())) throw new Error('FINANCE_FIELD_INVALID:beneficiary_user_id'); return Object.freeze({ id: String(r.id), companyId: text(r, 'company_id'), orderId: text(r, 'order_id'), beneficiaryUserId: beneficiary as string | null, entryType: eventType(r, 'entry_type', 'recognized') as ProfitEntry['entryType'], amount: money(r, 'profit_amount') }) }
const earning = (v: unknown): LaborEarning => { const r = obj(v); return Object.freeze({ id: String(r.id), companyId: text(r, 'company_id'), orderId: text(r, 'order_id'), beneficiaryUserId: text(r, 'beneficiary_user_id'), entryType: eventType(r, 'entry_type', 'recognized') as LaborEarning['entryType'], amount: money(r, 'labor_earning_amount') }) }
const refund = (v: unknown): RefundEvent => { const r = obj(v), event = text(r, 'event_type'); if (!['requested', 'approved', 'confirmed', 'reversed'].includes(event)) throw new Error('FINANCE_FIELD_INVALID:event_type'); return Object.freeze({ id: String(r.id), companyId: text(r, 'company_id'), orderId: text(r, 'order_id'), eventType: event as RefundEvent['eventType'], amount: money(r, 'refund_amount'), reason: text(r, 'reason') }) }
const withSignal = (request: any, signal?: AbortSignal) => signal ? request.abortSignal(signal) : request
export class SupabaseFinanceReader {
  async loadFinance(companyId: string, signal?: AbortSignal): Promise<FinanceData> { const c = getGreenfieldSupabase(); const [p, i, pr, rf] = await Promise.all([withSignal(c.from('payment_events').select('id,company_id,order_id,event_type,payment_amount').eq('company_id', companyId), signal), withSignal(c.from('internal_payment_events').select('id,company_id,order_id,event_type,internal_payment_amount').eq('company_id', companyId), signal), withSignal(c.from('profit_ledger_entries').select('id,company_id,order_id,beneficiary_user_id,entry_type,profit_amount').eq('company_id', companyId), signal), withSignal(c.from('refund_events').select('id,company_id,order_id,event_type,refund_amount,reason').eq('company_id', companyId), signal)]); const error = p.error ?? i.error ?? pr.error ?? rf.error; if (error) throw new Error(`FINANCE_QUERY_FAILED:${error.code ?? 'UNKNOWN'}`); return Object.freeze({ payments: Object.freeze((p.data ?? []).map(payment)), internalPayments: Object.freeze((i.data ?? []).map(internal)), profits: Object.freeze((pr.data ?? []).map(profit)), refunds: Object.freeze((rf.data ?? []).map(refund)) }) }
  async loadEarnings(companyId: string, signal?: AbortSignal): Promise<readonly LaborEarning[]> { const c = getGreenfieldSupabase(); const result = await withSignal(c.from('labor_earnings').select('id,company_id,order_id,beneficiary_user_id,entry_type,labor_earning_amount').eq('company_id', companyId), signal); if (result.error) throw new Error(`EARNINGS_QUERY_FAILED:${result.error.code ?? 'UNKNOWN'}`); return Object.freeze((result.data ?? []).map(earning)) }
}
