export { QuoteOrderDemo as default, QuoteOrderDemo } from './QuoteOrderDemo'
export { demoCatalog, demoQuote } from './demoData'
export { approveSpecialContent, calculateValidUntil, completeDemonstration, createChangeOrder, freezeAfterDepositConfirmation, hasSpecialContent, quoteTotal, submitQuote } from './workflow'
export type { CustomerGrade, DemoQuote, QuoteActionResult, QuoteChangeOrder, QuoteLine, QuoteSnapshot, QuoteStatus, VersionedCatalogItem } from './types'
export { QuoteOrderDataError } from './dataSource'
export type { DealOrderRecord, DealQuoteRecord, QuoteOrderDataSource } from './dataSource'
export { createSupabaseQuoteOrderDataSource } from './supabaseDataSource'
