-- Complete the order-backed performance center without trusting client totals.

create index if not exists order_performance_states_quarter_sales_qualified_idx
  on public.order_performance_states(team_id,attribution_quarter_start,salesperson_id)
  where status='qualified';

create index if not exists order_performance_events_latest_order_idx
  on public.order_performance_events(team_id,order_id,created_at desc,id desc);

-- Payment, reversal and cancellation rows are the trusted ledgers. Keep the
-- transition engine out of the exposed public schema and invoke it only from
-- database triggers, so a browser cannot manufacture qualification events.
create schema if not exists sales_os_private;
revoke all on schema sales_os_private from public,anon,authenticated,service_role;

create or replace function sales_os_private.refresh_order_performance_state_core(
  p_team_id text,
  p_order_id uuid,
  p_reason text,
  p_trigger_type text,
  p_trigger_id uuid,
  p_actor_id uuid
) returns void
language plpgsql security definer set search_path=''
as $refresh_order_performance_state_core$
declare
  v_order public.deal_orders;
  v_state public.order_performance_states;
  v_prior_event public.order_performance_events;
  v_event_type text;
  v_net_paid numeric;
  v_quarter_start date;
  v_is_cancelled boolean:=false;
  v_idempotency_key uuid;
begin
  if p_team_id is null
    or p_order_id is null
    or nullif(trim(p_reason),'') is null
    or p_trigger_type not in('payment','reversal','order','backfill')
    or p_trigger_id is null
    or (p_actor_id is null and p_trigger_type<>'backfill') then
    raise exception 'PERFORMANCE_TRIGGER_INPUT_REQUIRED' using errcode='22023';
  end if;

  select o.* into v_order
  from public.deal_orders o
  where o.team_id=p_team_id and o.id=p_order_id
  for update;
  if v_order.id is null then
    raise exception 'PERFORMANCE_TRIGGER_ORDER_NOT_FOUND' using errcode='P0002';
  end if;
  if p_actor_id is not null and not exists(
      select 1
      from public.profiles p
      where p.id=p_actor_id and p.team_id=p_team_id
    ) then
    raise exception 'PERFORMANCE_TRIGGER_ACTOR_MISMATCH' using errcode='42501';
  end if;
  if not public.is_feature_enabled(p_team_id,'sales_os_v3') then
    return;
  end if;

  -- Namespace the ledger row id by trigger type. This key is generated by the
  -- database and cannot be supplied by a client.
  v_idempotency_key:=md5(
    'order-performance:'||p_trigger_type||':'||p_trigger_id::text
  )::uuid;
  select e.* into v_prior_event
  from public.order_performance_events e
  where e.team_id=p_team_id and e.idempotency_key=v_idempotency_key;
  if v_prior_event.id is not null then
    if v_prior_event.order_id<>p_order_id
      or v_prior_event.trigger_type<>p_trigger_type
      or v_prior_event.trigger_id is distinct from p_trigger_id then
      raise exception 'PERFORMANCE_TRIGGER_IDEMPOTENCY_CONFLICT' using errcode='23505';
    end if;
    return;
  end if;

  select greatest(
    coalesce(sum(p.amount),0)-coalesce((
      select sum(r.amount)
      from public.deal_payment_reversals r
      join public.deal_payments rp
        on rp.id=r.payment_id and rp.team_id=r.team_id
      where rp.team_id=p_team_id and rp.order_id=p_order_id
    ),0),
    0
  ) into v_net_paid
  from public.deal_payments p
  where p.team_id=p_team_id and p.order_id=p_order_id;

  -- Cancellation is an append-only business record. It revokes performance
  -- even though the legacy cancellation RPC does not mutate deal_orders.status.
  select
    v_order.status='cancelled'
    or exists(
      select 1
      from public.deal_order_cancellations c
      where c.team_id=p_team_id and c.order_id=p_order_id
    )
  into v_is_cancelled;

  select s.* into v_state
  from public.order_performance_states s
  where s.team_id=p_team_id and s.order_id=p_order_id
  for update;
  if v_state.order_id is null then
    insert into public.order_performance_states(
      team_id,order_id,salesperson_id,sale_type,gmv_snapshot,
      points_snapshot,net_customer_paid
    ) values(
      v_order.team_id,v_order.id,v_order.salesperson_id_snapshot,
      v_order.sale_type_snapshot,v_order.performance_gmv_snapshot,
      v_order.performance_points_snapshot,v_net_paid
    )
    returning * into v_state;
  end if;

  if v_net_paid>=v_order.customer_total
    and not v_is_cancelled
    and v_state.status<>'qualified' then
    v_event_type:=case
      when v_state.first_qualified_at is null then 'qualified'
      else 'restored'
    end;
    v_quarter_start:=coalesce(
      v_state.attribution_quarter_start,
      date_trunc('quarter',(now() at time zone 'Asia/Shanghai'))::date
    );
    update public.order_performance_states s set
      status='qualified',
      attribution_quarter_start=v_quarter_start,
      net_customer_paid=v_net_paid,
      first_qualified_at=coalesce(s.first_qualified_at,now()),
      last_qualified_at=now(),
      revoked_at=null,
      updated_at=now()
    where s.team_id=p_team_id and s.order_id=p_order_id
    returning * into v_state;
  elsif (v_net_paid<v_order.customer_total or v_is_cancelled)
    and v_state.status='qualified' then
    v_event_type:='revoked';
    v_quarter_start:=v_state.attribution_quarter_start;
    update public.order_performance_states s set
      status='revoked',
      net_customer_paid=v_net_paid,
      revoked_at=now(),
      updated_at=now()
    where s.team_id=p_team_id and s.order_id=p_order_id
    returning * into v_state;
  else
    update public.order_performance_states s set
      net_customer_paid=v_net_paid,
      updated_at=now()
    where s.team_id=p_team_id and s.order_id=p_order_id;
    return;
  end if;

  insert into public.order_performance_events(
    team_id,order_id,event_type,attribution_quarter_start,reason,
    trigger_type,trigger_id,idempotency_key,salesperson_id,sale_type,
    gmv_snapshot,points_snapshot,net_customer_paid,actor_id
  ) values(
    v_order.team_id,v_order.id,v_event_type,v_quarter_start,trim(p_reason),
    p_trigger_type,p_trigger_id,v_idempotency_key,
    v_order.salesperson_id_snapshot,v_order.sale_type_snapshot,
    v_order.performance_gmv_snapshot,v_order.performance_points_snapshot,
    v_net_paid,p_actor_id
  );

  -- Live ledger transitions have a verified business actor and are mirrored to
  -- the global audit log. Migration backfill has no human actor; its immutable
  -- order_performance_events row is the audit trail, avoiding a forged actor.
  if p_actor_id is not null then
    insert into public.audit_logs(
      team_id,actor_id,action,target_type,target_id,before_data,after_data
    ) values(
      v_order.team_id,p_actor_id,'performance.order_'||v_event_type,
      'deal_order',v_order.id,'{}'::jsonb,
      jsonb_build_object(
        'status',v_state.status,
        'quarterStart',v_state.attribution_quarter_start,
        'gmv',v_state.gmv_snapshot,
        'points',v_state.points_snapshot,
        'netCustomerPaid',v_net_paid,
        'triggerType',p_trigger_type,
        'triggerId',p_trigger_id
      )
    );
  end if;
end
$refresh_order_performance_state_core$;

create or replace function sales_os_private.refresh_performance_after_payment()
returns trigger
language plpgsql security definer set search_path=''
as $refresh_performance_after_payment$
begin
  perform sales_os_private.refresh_order_performance_state_core(
    new.team_id,new.order_id,'customer_payment_confirmed','payment',new.id,new.confirmed_by
  );
  return new;
end
$refresh_performance_after_payment$;

create or replace function sales_os_private.refresh_performance_after_reversal()
returns trigger
language plpgsql security definer set search_path=''
as $refresh_performance_after_reversal$
declare
  v_order_id uuid;
begin
  select p.order_id into v_order_id
  from public.deal_payments p
  where p.team_id=new.team_id and p.id=new.payment_id;
  if v_order_id is null then
    raise exception 'PERFORMANCE_TRIGGER_PAYMENT_NOT_FOUND' using errcode='P0002';
  end if;
  perform sales_os_private.refresh_order_performance_state_core(
    new.team_id,v_order_id,'customer_payment_reversed','reversal',new.id,new.confirmed_by
  );
  return new;
end
$refresh_performance_after_reversal$;

create or replace function sales_os_private.refresh_performance_after_cancellation()
returns trigger
language plpgsql security definer set search_path=''
as $refresh_performance_after_cancellation$
begin
  perform sales_os_private.refresh_order_performance_state_core(
    new.team_id,new.order_id,'order_cancellation_recorded','order',new.id,new.created_by
  );
  return new;
end
$refresh_performance_after_cancellation$;

drop trigger if exists refresh_performance_after_payment on public.deal_payments;
create trigger refresh_performance_after_payment
after insert on public.deal_payments
for each row execute function sales_os_private.refresh_performance_after_payment();

drop trigger if exists refresh_performance_after_reversal on public.deal_payment_reversals;
create trigger refresh_performance_after_reversal
after insert on public.deal_payment_reversals
for each row execute function sales_os_private.refresh_performance_after_reversal();

drop trigger if exists refresh_performance_after_cancellation on public.deal_order_cancellations;
create trigger refresh_performance_after_cancellation
after insert on public.deal_order_cancellations
for each row execute function sales_os_private.refresh_performance_after_cancellation();

revoke all on function sales_os_private.refresh_order_performance_state_core(
  text,uuid,text,text,uuid,uuid
) from public,anon,authenticated,service_role;
revoke all on function sales_os_private.refresh_performance_after_payment()
  from public,anon,authenticated,service_role;
revoke all on function sales_os_private.refresh_performance_after_reversal()
  from public,anon,authenticated,service_role;
revoke all on function sales_os_private.refresh_performance_after_cancellation()
  from public,anon,authenticated,service_role;

-- The earlier public repair RPC accepted caller-supplied trigger metadata.
-- Automatic ledger triggers supersede it; keep the symbol for migration
-- compatibility but remove every Data API execution path.
revoke all on function public.refresh_order_performance_state(
  uuid,text,text,uuid,uuid
) from public,anon,authenticated,service_role;

-- Idempotent migration-time backfill. Existing formal orders are recalculated
-- from the payment/reversal/cancellation ledgers; an empty production set is a
-- safe no-op. The order id is stable and is namespaced as a backfill trigger.
do $backfill_order_performance$
declare
  v_order record;
begin
  for v_order in
    select o.team_id,o.id
    from public.deal_orders o
    order by o.team_id,o.id
  loop
    perform sales_os_private.refresh_order_performance_state_core(
      v_order.team_id,
      v_order.id,
      'migration_backfill_current_ledger',
      'backfill',
      v_order.id,
      null
    );
  end loop;
end
$backfill_order_performance$;

create or replace function public.set_quarterly_performance_target(
  p_profile_id uuid,
  p_quarter_start date,
  p_points_target numeric,
  p_new_gmv_target numeric,
  p_renewal_gmv_target numeric
) returns public.performance_quarterly_targets
language plpgsql security definer set search_path=''
as $set_quarterly_performance_target$
declare
  v_actor public.profiles;
  v_target_profile public.profiles;
  v_before public.performance_quarterly_targets;
  v_after public.performance_quarterly_targets;
  v_before_json jsonb;
begin
  if p_profile_id is null
    or p_quarter_start is null
    or p_points_target is null
    or p_new_gmv_target is null
    or p_renewal_gmv_target is null
    or p_points_target<0
    or p_new_gmv_target<0
    or p_renewal_gmv_target<0
    or p_quarter_start<>date_trunc('quarter',p_quarter_start)::date then
    raise exception 'INVALID_TARGET' using errcode='22023';
  end if;

  select p.* into v_actor
  from public.profiles p
  where p.id=auth.uid() and p.status='active';

  select p.* into v_target_profile
  from public.profiles p
  where p.id=p_profile_id
    and p.team_id=v_actor.team_id
    and p.status='active'
    and exists(
      select 1
      from public.profile_access_roles par
      join public.access_roles ar
        on ar.id=par.role_id and ar.team_id=par.team_id
      where par.team_id=p.team_id
        and par.profile_id=p.id
        and ar.code='sales'
    );

  if v_actor.id is null
    or v_target_profile.id is null
    or not public.is_feature_enabled(v_actor.team_id,'sales_os_v3')
    or not(
      public.can_supervise_performance(
        v_actor.team_id,p_profile_id,(now() at time zone 'Asia/Shanghai')::date
      )
      or public.has_access_role(v_actor.team_id,array['owner','admin'])
    ) then
    raise exception 'TARGET_FORBIDDEN' using errcode='42501';
  end if;

  select t.* into v_before
  from public.performance_quarterly_targets t
  where t.team_id=v_actor.team_id
    and t.profile_id=p_profile_id
    and t.quarter_start=p_quarter_start
  for update;
  v_before_json:=case when v_before.id is null then null else to_jsonb(v_before) end;

  insert into public.performance_quarterly_targets(
    team_id,profile_id,quarter_start,points_target,new_gmv_target,
    renewal_gmv_target,updated_by
  ) values(
    v_actor.team_id,p_profile_id,p_quarter_start,p_points_target,
    p_new_gmv_target,p_renewal_gmv_target,v_actor.id
  )
  on conflict(team_id,profile_id,quarter_start) do update set
    points_target=excluded.points_target,
    new_gmv_target=excluded.new_gmv_target,
    renewal_gmv_target=excluded.renewal_gmv_target,
    updated_by=v_actor.id,
    updated_at=now()
  returning * into v_after;

  insert into public.performance_target_events(
    team_id,target_id,event_type,snapshot,actor_id
  ) values(
    v_after.team_id,v_after.id,'target_set',
    jsonb_build_object('before',v_before_json,'after',to_jsonb(v_after)),v_actor.id
  );

  insert into public.audit_logs(
    team_id,actor_id,action,target_type,target_id,before_data,after_data
  ) values(
    v_after.team_id,v_actor.id,'performance.target_set','performance_target',v_after.id,
    coalesce(v_before_json,'{}'::jsonb),to_jsonb(v_after)
  );
  return v_after;
end
$set_quarterly_performance_target$;

create or replace function public.get_performance_center_snapshot(
  p_quarter_start date,
  p_scope text default 'personal',
  p_profile_id uuid default null
) returns jsonb
language plpgsql security definer stable set search_path=''
as $get_performance_center_snapshot$
declare
  v_actor public.profiles;
  v_scope text:=lower(coalesce(trim(p_scope),''));
  v_effective_scope text:=lower(coalesce(trim(p_scope),''));
  v_selected_profile_id uuid;
  v_is_owner_admin boolean:=false;
  v_can_read_all boolean:=false;
  v_can_manage_all boolean:=false;
  v_has_active_subordinates boolean:=false;
  v_actor_is_sales boolean:=false;
  v_result jsonb;
begin
  if p_quarter_start is null
    or p_quarter_start<>date_trunc('quarter',p_quarter_start)::date then
    raise exception 'INVALID_QUARTER' using errcode='22023';
  end if;
  if v_scope not in('personal','team') then
    raise exception 'INVALID_PERFORMANCE_SCOPE' using errcode='22023';
  end if;
  if v_scope='team' and p_profile_id is not null then
    raise exception 'TEAM_PROFILE_FILTER_NOT_ALLOWED' using errcode='22023';
  end if;

  select p.* into v_actor
  from public.profiles p
  where p.id=auth.uid() and p.status='active';
  if v_actor.id is null
    or not public.is_feature_enabled(v_actor.team_id,'sales_os_v3') then
    raise exception 'PERFORMANCE_FORBIDDEN' using errcode='42501';
  end if;

  v_is_owner_admin:=public.has_access_role(v_actor.team_id,array['owner','admin']);
  v_can_read_all:=v_is_owner_admin or public.has_permission(v_actor.team_id,'finance.read');
  v_can_manage_all:=v_is_owner_admin;
  select exists(
    select 1
    from public.performance_supervisor_assignments a
    where a.team_id=v_actor.team_id
      and a.supervisor_id=v_actor.id
      and (now() at time zone 'Asia/Shanghai')::date>=a.starts_on
      and (a.ends_on is null or (now() at time zone 'Asia/Shanghai')::date<=a.ends_on)
  ) into v_has_active_subordinates;
  select exists(
    select 1
    from public.profile_access_roles par
    join public.access_roles ar
      on ar.id=par.role_id and ar.team_id=par.team_id
    where par.team_id=v_actor.team_id
      and par.profile_id=v_actor.id
      and ar.code='sales'
  ) into v_actor_is_sales;

  if v_scope='personal' then
    if p_profile_id is null and not v_actor_is_sales then
      -- Management users may land on the default personal tab before choosing
      -- a salesperson. Fall back to their authorized team view instead of
      -- looking up their own non-sales profile as a salesperson.
      if v_can_read_all or v_has_active_subordinates then
        v_effective_scope:='team';
        v_selected_profile_id:=null;
      else
        raise exception 'PERFORMANCE_FORBIDDEN' using errcode='42501';
      end if;
    else
      v_selected_profile_id:=coalesce(p_profile_id,v_actor.id);
      if not exists(
        select 1
        from public.profiles p
        where p.id=v_selected_profile_id
          and p.team_id=v_actor.team_id
          and p.status='active'
          and exists(
            select 1
            from public.profile_access_roles par
            join public.access_roles ar
              on ar.id=par.role_id and ar.team_id=par.team_id
            where par.team_id=p.team_id
              and par.profile_id=p.id
              and ar.code='sales'
          )
      ) then
        raise exception 'PERFORMANCE_PROFILE_NOT_FOUND' using errcode='P0002';
      end if;
      if v_selected_profile_id<>v_actor.id
        and not v_can_read_all
        and not public.can_supervise_performance(
          v_actor.team_id,v_selected_profile_id,(now() at time zone 'Asia/Shanghai')::date
        ) then
        raise exception 'PERFORMANCE_FORBIDDEN' using errcode='42501';
      end if;
    end if;
  elsif not v_can_read_all and not v_has_active_subordinates then
    raise exception 'TEAM_PERFORMANCE_FORBIDDEN' using errcode='42501';
  end if;

  with visible_people as materialized(
    select p.id,p.name
    from public.profiles p
    where p.team_id=v_actor.team_id
      and p.status='active'
      and exists(
        select 1
        from public.profile_access_roles par
        join public.access_roles ar
          on ar.id=par.role_id and ar.team_id=par.team_id
        where par.team_id=p.team_id
          and par.profile_id=p.id
          and ar.code='sales'
      )
      and case
        when v_effective_scope='personal' then p.id=v_selected_profile_id
        when v_can_read_all then true
        else p.id=v_actor.id or public.can_supervise_performance(
          v_actor.team_id,p.id,(now() at time zone 'Asia/Shanghai')::date
        )
      end
  ), qualified_states as materialized(
    select s.*
    from public.order_performance_states s
    join visible_people p on p.id=s.salesperson_id
    where s.team_id=v_actor.team_id
      and s.attribution_quarter_start=p_quarter_start
      and s.status='qualified'
  ), member_rows as materialized(
    select
      p.id profile_id,
      p.name profile_name,
      coalesce(sum(s.points_snapshot),0)::numeric points_actual,
      coalesce(sum(s.gmv_snapshot) filter(where s.sale_type='new'),0)::numeric new_gmv_actual,
      coalesce(sum(s.gmv_snapshot) filter(where s.sale_type='renewal'),0)::numeric renewal_gmv_actual,
      coalesce(t.points_target,0)::numeric points_target,
      coalesce(t.new_gmv_target,0)::numeric new_gmv_target,
      coalesce(t.renewal_gmv_target,0)::numeric renewal_gmv_target,
      (
        v_can_manage_all
        or public.can_supervise_performance(
          v_actor.team_id,p.id,(now() at time zone 'Asia/Shanghai')::date
        )
      ) can_set_target
    from visible_people p
    left join qualified_states s on s.salesperson_id=p.id
    left join public.performance_quarterly_targets t
      on t.team_id=v_actor.team_id
      and t.profile_id=p.id
      and t.quarter_start=p_quarter_start
    group by p.id,p.name,t.points_target,t.new_gmv_target,t.renewal_gmv_target
  ), product_rows as materialized(
    select
      ql.source_item_id catalog_item_id,
      ql.item_name_snapshot product_name,
      count(distinct s.order_id)::integer order_count,
      coalesce(sum(ql.quantity),0)::numeric quantity,
      coalesce(sum(ql.points_snapshot*ql.quantity),0)::numeric points,
      coalesce(sum(ql.customer_unit_price*ql.quantity),0)::numeric gmv
    from qualified_states s
    join public.deal_orders o
      on o.team_id=s.team_id and o.id=s.order_id
    join public.deal_quote_lines ql
      on ql.team_id=o.team_id and ql.quote_id=o.quote_id
    group by ql.source_item_id,ql.item_name_snapshot
  ), order_rows as materialized(
    select
      o.id order_id,
      o.order_number,
      coalesce(st.name,'未命名客户') customer_name,
      s.salesperson_id,
      p.name salesperson_name,
      s.sale_type,
      s.points_snapshot points,
      s.gmv_snapshot gmv,
      coalesce(e.created_at,s.last_qualified_at,s.first_qualified_at,s.updated_at) counted_at,
      case
        when e.event_type='restored' then 'restored'
        when e.event_type='revoked' or s.status='revoked' then 'reversed'
        else 'counted'
      end status
    from public.order_performance_states s
    join visible_people p on p.id=s.salesperson_id
    join public.deal_orders o on o.team_id=s.team_id and o.id=s.order_id
    left join public.crm_opportunities op
      on op.team_id=o.team_id and op.id=o.opportunity_id
    left join public.crm_stores st
      on st.team_id=op.team_id and st.id=op.store_id
    left join lateral(
      select pe.event_type,pe.created_at
      from public.order_performance_events pe
      where pe.team_id=s.team_id and pe.order_id=s.order_id
      order by pe.created_at desc,pe.id desc
      limit 1
    ) e on true
    where s.team_id=v_actor.team_id
      and s.attribution_quarter_start=p_quarter_start
      and s.status in('qualified','revoked')
  )
  select jsonb_build_object(
    'viewer',jsonb_build_object(
      'profileId',v_actor.id,
      'teamId',v_actor.team_id,
      'requestedScope',v_scope,
      'effectiveScope',v_effective_scope,
      'selectedProfileId',v_selected_profile_id,
      'canManageTargets',v_can_manage_all or v_has_active_subordinates
    ),
    'summary',jsonb_build_object(
      'quarterStart',p_quarter_start,
      'points',jsonb_build_object(
        'target',coalesce((select sum(m.points_target) from member_rows m),0),
        'actual',coalesce((select sum(m.points_actual) from member_rows m),0)
      ),
      'newGmv',jsonb_build_object(
        'target',coalesce((select sum(m.new_gmv_target) from member_rows m),0),
        'actual',coalesce((select sum(m.new_gmv_actual) from member_rows m),0)
      ),
      'renewalGmv',jsonb_build_object(
        'target',coalesce((select sum(m.renewal_gmv_target) from member_rows m),0),
        'actual',coalesce((select sum(m.renewal_gmv_actual) from member_rows m),0)
      )
    ),
    'members',coalesce((
      select jsonb_agg(jsonb_build_object(
        'profileId',m.profile_id,
        'profileName',m.profile_name,
        'points',m.points_actual,
        'newGmv',m.new_gmv_actual,
        'renewalGmv',m.renewal_gmv_actual,
        'pointsTarget',m.points_target,
        'newGmvTarget',m.new_gmv_target,
        'renewalGmvTarget',m.renewal_gmv_target,
        'canSetTarget',m.can_set_target
      ) order by m.profile_name,m.profile_id)
      from member_rows m
    ),'[]'::jsonb),
    'products',coalesce((
      select jsonb_agg(jsonb_build_object(
        'catalogItemId',pr.catalog_item_id,
        'productName',pr.product_name,
        'orderCount',pr.order_count,
        'quantity',pr.quantity,
        'points',pr.points,
        'gmv',pr.gmv
      ) order by pr.gmv desc,pr.product_name)
      from product_rows pr
    ),'[]'::jsonb),
    'orders',coalesce((
      select jsonb_agg(jsonb_build_object(
        'orderId',o.order_id,
        'orderNumber',o.order_number,
        'customerName',o.customer_name,
        'salespersonId',o.salesperson_id,
        'salespersonName',o.salesperson_name,
        'saleType',o.sale_type,
        'points',o.points,
        'gmv',o.gmv,
        'countedAt',o.counted_at,
        'status',o.status
      ) order by o.counted_at desc,o.order_id)
      from order_rows o
    ),'[]'::jsonb)
  ) into v_result;

  return v_result;
end
$get_performance_center_snapshot$;

-- Keep the legacy management RPC compatible while sourcing actuals only from
-- currently qualified order snapshots. Revoked orders disappear immediately;
-- restored orders are counted again by their retained attribution quarter.
create or replace function public.get_performance_management_dashboard(p_quarter_start date)
returns table(
  profile_id uuid,
  profile_name text,
  quarter_start date,
  points_target numeric,
  estimated_points numeric,
  official_points numeric,
  new_gmv_target numeric,
  new_gmv_actual numeric,
  renewal_gmv_target numeric,
  renewal_gmv_actual numeric,
  monthly_observations jsonb,
  can_set_target boolean
)
language plpgsql security definer stable set search_path=''
as $get_performance_management_dashboard$
declare
  v_profile public.profiles;
begin
  if p_quarter_start is null
    or p_quarter_start<>date_trunc('quarter',p_quarter_start)::date then
    raise exception 'INVALID_QUARTER' using errcode='22023';
  end if;
  select p.* into v_profile
  from public.profiles p
  where p.id=auth.uid() and p.status='active';
  if v_profile.id is null
    or not public.is_feature_enabled(v_profile.team_id,'sales_os_v3') then
    raise exception 'PERFORMANCE_FORBIDDEN' using errcode='42501';
  end if;

  return query
  with people as materialized(
    select p.id,p.name
    from public.profiles p
    where p.team_id=v_profile.team_id
      and p.status='active'
      and exists(
        select 1
        from public.profile_access_roles par
        join public.access_roles ar
          on ar.id=par.role_id and ar.team_id=par.team_id
        where par.team_id=p.team_id and par.profile_id=p.id and ar.code='sales'
      )
      and(
        p.id=v_profile.id
        or public.can_supervise_performance(
          v_profile.team_id,p.id,(now() at time zone 'Asia/Shanghai')::date
        )
        or public.has_access_role(v_profile.team_id,array['owner','admin'])
        or public.has_permission(v_profile.team_id,'finance.read')
      )
  ), actuals as materialized(
    select
      s.salesperson_id,
      coalesce(sum(s.points_snapshot),0)::numeric points,
      coalesce(sum(s.gmv_snapshot) filter(where s.sale_type='new'),0)::numeric new_gmv,
      coalesce(sum(s.gmv_snapshot) filter(where s.sale_type='renewal'),0)::numeric renewal_gmv
    from public.order_performance_states s
    join people p on p.id=s.salesperson_id
    where s.team_id=v_profile.team_id
      and s.attribution_quarter_start=p_quarter_start
      and s.status='qualified'
    group by s.salesperson_id
  ), months as(
    select generate_series(
      p_quarter_start,p_quarter_start+interval '2 months',interval '1 month'
    )::date month_start
  )
  select
    p.id,
    p.name,
    p_quarter_start,
    coalesce(t.points_target,0),
    coalesce((
      select sum(o.estimated_points)
      from public.performance_monthly_observations o
      where o.team_id=v_profile.team_id
        and o.profile_id=p.id
        and o.month_start between p_quarter_start and p_quarter_start+interval '2 months'
    ),t.estimated_points,0),
    coalesce(a.points,0),
    coalesce(t.new_gmv_target,0),
    coalesce(a.new_gmv,0),
    coalesce(t.renewal_gmv_target,0),
    coalesce(a.renewal_gmv,0),
    (
      select jsonb_agg(jsonb_build_object(
        'month_start',m.month_start,
        'estimated_points',coalesce(o.estimated_points,0),
        'new_gmv',coalesce(x.new_gmv,0),
        'renewal_gmv',coalesce(x.renewal_gmv,0),
        'official_points',coalesce(x.points,0)
      ) order by m.month_start)
      from months m
      left join public.performance_monthly_observations o
        on o.team_id=v_profile.team_id
        and o.profile_id=p.id
        and o.month_start=m.month_start
      left join lateral(
        select
          coalesce(sum(s.points_snapshot),0)::numeric points,
          coalesce(sum(s.gmv_snapshot) filter(where s.sale_type='new'),0)::numeric new_gmv,
          coalesce(sum(s.gmv_snapshot) filter(where s.sale_type='renewal'),0)::numeric renewal_gmv
        from public.order_performance_states s
        where s.team_id=v_profile.team_id
          and s.salesperson_id=p.id
          and s.status='qualified'
          and s.attribution_quarter_start=p_quarter_start
          and date_trunc('month',coalesce(s.last_qualified_at,s.first_qualified_at))::date=m.month_start
      ) x on true
    ),
    (
      public.can_supervise_performance(
        v_profile.team_id,p.id,(now() at time zone 'Asia/Shanghai')::date
      )
      or public.has_access_role(v_profile.team_id,array['owner','admin'])
    )
  from people p
  left join public.performance_quarterly_targets t
    on t.team_id=v_profile.team_id
    and t.profile_id=p.id
    and t.quarter_start=p_quarter_start
  left join actuals a on a.salesperson_id=p.id
  order by p.name,p.id;
end
$get_performance_management_dashboard$;

revoke all on function public.set_quarterly_performance_target(
  uuid,date,numeric,numeric,numeric
) from public,anon;
grant execute on function public.set_quarterly_performance_target(
  uuid,date,numeric,numeric,numeric
) to authenticated;

revoke all on function public.get_performance_center_snapshot(date,text,uuid)
  from public,anon;
grant execute on function public.get_performance_center_snapshot(date,text,uuid)
  to authenticated;

revoke all on function public.get_performance_management_dashboard(date)
  from public,anon;
grant execute on function public.get_performance_management_dashboard(date)
  to authenticated;

notify pgrst,'reload schema';
