-- Controlled CRM mutations for the 3.0 sales workbench. No table is writable through these functions without server checks.
create or replace function public.upsert_crm_brand(p_id uuid,p_name text,p_business_mode text default 'independent') returns uuid
language plpgsql security definer set search_path='' as $$declare r public.profiles;b public.crm_brands;begin
 select * into r from public.profiles where id=auth.uid() and status='active';
 if r.id is null or not public.is_feature_enabled(r.team_id,'sales_os_v3') or not public.has_permission(r.team_id,'customers.manage') then raise exception 'CRM_MANAGE_FORBIDDEN' using errcode='42501';end if;
 if nullif(trim(p_name),'') is null or p_business_mode not in('independent','direct_chain','franchise_chain') then raise exception 'INVALID_BRAND' using errcode='22023';end if;
 if p_id is null then insert into public.crm_brands(team_id,name,business_mode,owner_id,created_by)values(r.team_id,trim(p_name),p_business_mode,r.id,r.id)returning * into b;
 else select * into b from public.crm_brands where id=p_id for update;if b.id is null or b.team_id<>r.team_id or not(b.owner_id=r.id or public.has_permission(r.team_id,'customers.supervise'))then raise exception 'BRAND_FORBIDDEN' using errcode='42501';end if;update public.crm_brands set name=trim(p_name),business_mode=p_business_mode,updated_at=now()where id=p_id returning * into b;end if;return b.id;end$$;

create or replace function public.upsert_crm_store(p_id uuid,p_brand_id uuid,p_region_id uuid,p_name text,p_business_type text,p_address text default null) returns uuid
language plpgsql security definer set search_path='' as $$declare r public.profiles;s public.crm_stores;begin
 select * into r from public.profiles where id=auth.uid() and status='active';if r.id is null or not public.has_permission(r.team_id,'customers.manage')or not public.crm_can_access_region(r.team_id,p_region_id,r.id)then raise exception 'STORE_REGION_FORBIDDEN' using errcode='42501';end if;
 if nullif(trim(p_name),'')is null or p_business_type not in('fast_food','chinese','hotpot','barbecue','beverage','bakery','banquet','international')or not exists(select 1 from public.crm_brands b where b.id=p_brand_id and b.team_id=r.team_id)then raise exception 'INVALID_STORE' using errcode='22023';end if;
 if p_id is null then insert into public.crm_stores(team_id,brand_id,region_id,name,address,business_type,owner_id,created_by)values(r.team_id,p_brand_id,p_region_id,trim(p_name),nullif(trim(p_address),''),p_business_type,r.id,r.id)returning * into s;
 else select * into s from public.crm_stores where id=p_id for update;if s.id is null or s.team_id<>r.team_id or not(s.owner_id=r.id or public.has_permission(r.team_id,'customers.supervise'))then raise exception 'STORE_FORBIDDEN' using errcode='42501';end if;update public.crm_stores set brand_id=p_brand_id,region_id=p_region_id,name=trim(p_name),address=nullif(trim(p_address),''),business_type=p_business_type,updated_at=now()where id=p_id returning * into s;end if;return s.id;end$$;

create or replace function public.upsert_crm_contact(p_id uuid,p_brand_id uuid,p_store_id uuid,p_name text,p_title text,p_is_key_person boolean default false) returns uuid
language plpgsql security definer set search_path='' as $$declare r public.profiles;c public.crm_contacts;begin
 select * into r from public.profiles where id=auth.uid()and status='active';if r.id is null or not public.has_permission(r.team_id,'customers.manage')then raise exception 'CONTACT_FORBIDDEN' using errcode='42501';end if;
 if nullif(trim(p_name),'')is null or(p_brand_id is null and p_store_id is null)or(p_store_id is not null and not exists(select 1 from public.crm_stores s where s.id=p_store_id and s.team_id=r.team_id and public.crm_can_access_region(s.team_id,s.region_id,s.owner_id)))then raise exception 'INVALID_CONTACT' using errcode='22023';end if;
 if p_id is null then insert into public.crm_contacts(team_id,brand_id,store_id,name,title,is_key_person,owner_id,created_by)values(r.team_id,p_brand_id,p_store_id,trim(p_name),nullif(trim(p_title),''),p_is_key_person,r.id,r.id)returning * into c;
 else select * into c from public.crm_contacts where id=p_id for update;if c.id is null or c.team_id<>r.team_id or not(c.owner_id=r.id or public.has_permission(r.team_id,'customers.supervise'))then raise exception 'CONTACT_FORBIDDEN' using errcode='42501';end if;update public.crm_contacts set brand_id=p_brand_id,store_id=p_store_id,name=trim(p_name),title=nullif(trim(p_title),''),is_key_person=p_is_key_person,updated_at=now()where id=p_id returning * into c;end if;return c.id;end$$;

create or replace function public.upsert_crm_lead(p_id uuid,p_region_id uuid,p_brand_id uuid,p_store_id uuid,p_title text,p_source text default null) returns uuid
language plpgsql security definer set search_path='' as $$declare r public.profiles;l public.crm_leads;begin
 select * into r from public.profiles where id=auth.uid()and status='active';if r.id is null or not public.has_permission(r.team_id,'customers.manage')or not public.crm_can_access_region(r.team_id,p_region_id,r.id)then raise exception 'LEAD_REGION_FORBIDDEN' using errcode='42501';end if;
 if nullif(trim(p_title),'')is null then raise exception 'INVALID_LEAD' using errcode='22023';end if;
 if p_id is null then insert into public.crm_leads(team_id,region_id,brand_id,store_id,title,source,status,owner_id,claimed_at,created_by)values(r.team_id,p_region_id,p_brand_id,p_store_id,trim(p_title),nullif(trim(p_source),''),'claimed',r.id,now(),r.id)returning * into l;
 else select * into l from public.crm_leads where id=p_id for update;if l.id is null or l.team_id<>r.team_id or not(l.owner_id=r.id or public.has_permission(r.team_id,'customers.supervise'))then raise exception 'LEAD_FORBIDDEN' using errcode='42501';end if;update public.crm_leads set region_id=p_region_id,brand_id=p_brand_id,store_id=p_store_id,title=trim(p_title),source=nullif(trim(p_source),''),updated_at=now()where id=p_id returning * into l;end if;return l.id;end$$;

create or replace function public.qualify_crm_lead(p_lead_id uuid,p_value_grade text,p_annual_fee_viable boolean,p_key_person_contacted boolean,p_key_person_meeting_at timestamptz default null) returns uuid
language plpgsql security definer set search_path='' as $$declare r public.profiles;l public.crm_leads;s public.crm_stores;o public.crm_opportunities;begin
 select * into r from public.profiles where id=auth.uid()and status='active';select * into l from public.crm_leads where id=p_lead_id for update;
 if r.id is null or l.id is null or l.team_id<>r.team_id or not public.has_permission(r.team_id,'customers.manage')or not(l.owner_id=r.id or public.can_act_for(r.team_id,l.owner_id)or public.has_permission(r.team_id,'customers.supervise'))or not public.crm_can_access_region(l.team_id,l.region_id,l.owner_id)then raise exception 'QUALIFY_FORBIDDEN' using errcode='42501';end if;
 select * into s from public.crm_stores where id=l.store_id and team_id=l.team_id;if s.id is null or s.store_status='closed'then raise exception 'REAL_STORE_REQUIRED' using errcode='22023';end if;
 if p_value_grade not in('A','B','C')or not coalesce(p_annual_fee_viable,false)or not(coalesce(p_key_person_contacted,false)or p_key_person_meeting_at is not null)then raise exception 'OPPORTUNITY_QUALIFICATION_FAILED' using errcode='22023';end if;
 insert into public.crm_opportunities(team_id,lead_id,brand_id,store_id,region_id,owner_id,value_grade,annual_fee_viable,key_person_contacted,key_person_meeting_at,created_by)values(l.team_id,l.id,l.brand_id,l.store_id,l.region_id,l.owner_id,p_value_grade,true,p_key_person_contacted,p_key_person_meeting_at,r.id)returning * into o;
 if not o.qualification_valid then raise exception 'OPPORTUNITY_QUALIFICATION_FAILED' using errcode='22023';end if;update public.crm_leads set status='qualified',updated_at=now()where id=l.id;return o.id;end$$;

revoke all on function public.upsert_crm_brand(uuid,text,text),public.upsert_crm_store(uuid,uuid,uuid,text,text,text),public.upsert_crm_contact(uuid,uuid,uuid,text,text,boolean),public.upsert_crm_lead(uuid,uuid,uuid,uuid,text,text),public.qualify_crm_lead(uuid,text,boolean,boolean,timestamptz) from public;
grant execute on function public.upsert_crm_brand(uuid,text,text),public.upsert_crm_store(uuid,uuid,uuid,text,text,text),public.upsert_crm_contact(uuid,uuid,uuid,text,text,boolean),public.upsert_crm_lead(uuid,uuid,uuid,uuid,text,text),public.qualify_crm_lead(uuid,text,boolean,boolean,timestamptz) to authenticated;
notify pgrst,'reload schema';
